### ISSUE TITLE
Non capturing groups (?=...), (?!...) support

### ISSUE THREAD

**Issue by doskabouter** [andgineer/TRegExpr#1]
Is it possible to add an option to use non-capturing groups?
either with ?: or /n

**Comment by TommySlokky** [comment]
It would be a great addition...

**Comment by Alexey-T** [comment]
I also need this in CudaText app.

**Comment by Alexey-T** [comment]
@doskabouter @TommySlokky Try my pull request at #23

**Comment by andgineer** [comment]
merged
