### ISSUE TITLE
 UNHANDLED EXCEPTION!!! TRegExpr(comp): Urecognized Modifier (pos 10)

### ISSUE THREAD

**Issue by chevant0n** [andgineer/TRegExpr#10]
^(?!([0-9])\1{9})[0-9]{10}$

1111111111 - not ok
1111111112 - ok

**Comment by andgineer** [comment]
It does not support look-ahead
https://regex.sorokin.engineer/en/latest/faq.html#regular-expressions-with-do-not-work

**Comment by andgineer** [comment]
Duplicates
https://github.com/andgineer/TRegExpr/issues/1
