### ISSUE TITLE
Exec with TryOnce

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#108]
I will add TryOnce exec, exec which tests only at Offset (not in loop). it's needed for lexer parser which must test only one offset, outter code must change offset then (sometimes by 1, sometimes by n).

to add ATryOnce, i will change code near `if reganchored <> #0` in MatchPrim

Ok naming?
ExecPos(AOffset: integer; ATryOnce: boolean)

**Comment by andgineer** [comment]
Exec calls ExecPrim and it search just first re match and exit.
It does not loop - you should use ExecNext in loop to find all matches.

**Comment by Alexey-T** [comment]
Ok, I will add this func with some testing

**Comment by andgineer** [comment]
Why do you need it?
Exec func do not iterate by itself.
And if will I do not understan where will you place results for all matches?

**Comment by Alexey-T** [comment]
Pull req. зачем это нужно. я делаю парсер анализа исходника который разбивает код программы на "токены". для этого для каждой offset  мне надо програть офсет по Н правилам (Н regex objects) - найти первое правило которое "матчит" в этом оффсет.

**Comment by Alexey-T** [comment]
Это уже умеет делать EControl RegExpr - а ваш пока не умеет, вот и добавим это

**Comment by andgineer** [comment]
Почему не вызвать ExecPos поочередно с каждым правилом для конкретной позиции?
Не хочется чтобы она сдвигалась с указанной позиции?
Для этого есть MatchPrim.

**Comment by Alexey-T** [comment]
MatchPrim приватно. надо какую то обертку делать. ее можно сделать и над ExecPrim, и даже так лучше- там всякие проверки в начале которые нужны, и потом когда нашло- ExecPrim заносит ответ в startp/endp

**Comment by Alexey-T** [comment]
Да, нужно чтобы не было сдвига с позиции, был только тест в Offset

**Comment by Alexey-T** [comment]
@andgineer Добавил демо для теста! оно ищет то что и парсер-- все "токены" в коде паскаля по где-то 7 правилам

**Comment by andgineer** [comment]
ok теперь понятно
