### ISSUE TITLE
Remove regstart optimization

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#119]
ToDo.txt file tells it.
Why to remove?

- regstart works only if only ONE branch is in code. it dont work for `aa|bb|dd`. 
- it also dont work for `a+bb` because it needs first operator = EXACTLY (this example has first operator PLUS). 
- it dont work for (?i) mode because first operator is EXACTLYCI
- FirstCharSet does the same and better
- FirstCharSet computed in Unicode mode too (now!)

will remove it, ok?

**Comment by andgineer** [comment]
you are right - regstart now can be removed
