### ISSUE TITLE
Need error for unmatched {}

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#127]
1.
`d{`
gives opcode
exactly(d)
exactly({)

2. 
`d{}`
gives opcode
exactly(d)
exactly({})

@andgineer Maybe raise err here?

**Comment by andgineer** [comment]
I am not sure
https://regex.sorokin.engineer/en/latest/regular_expressions.html#quantification
...If a curly bracket occurs in any other context, it is treated as a regular character...

You are right that if we raise error here it would be more transparent to look for the error in re (if we forget closing curly brace).

But we will break backward compatibility and I am not sure that this transparency worth it..

On the other hand may be we there are no significant amount of old re with such a trick (opening curly brace without closing one) so backward compatibility does not matter.

So please decide by yourself.

**Comment by Alexey-T** [comment]
Most regular expression flavors treat the brace { as a literal character, unless it is part of a repetition operator like a{1,3}. So you generally do not need to escape it with a backslash, though you can do so if you want. But there are a few exceptions. Java requires literal opening braces to be escaped. Boost and std::regex require all literal braces to be escaped.

https://www.regular-expressions.info/characters.html

So it's ok to require ESCAPED {

**Comment by Alexey-T** [comment]
Don't know how to write test- if like this, we don't get error msg at all
```
procedure TTestRegexpr.TestBadBraces;
begin
  try
    CompileRE('d{');
    IsTrue('Not raised Error for braces', False);
  except
  end;

  try
    CompileRE('d{2,');
    IsTrue('Not raised Error for braces', False);
  except
  end;

  try
    CompileRE('d{}');
    IsTrue('Not raised Error for braces', False);
  except
  end;
end;
```
@andgineer

**Comment by andgineer** [comment]
Easy - you fail after try-except block (if no exception) - raise exception as last line of the subroutine.
Or you return in except block - success, you never be on the last line of the subroutine.
