### ISSUE TITLE
Strange flag value found

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#131]
```
        if BracesMin > 0 then
          flagp := flag_Worst; //???
        if Bracesmax > 0 then
          flagp := flagp or flag_HasWidth or flag_SpecStart;
```
??? is my mark - it SEEMS that flag_HasWidth was needed here? why flag_Worst=0? if BracesMin>0 then match has at least 1 char so flag_HasWidth needed.

**Comment by andgineer** [comment]
Looks like a bug but better check this.

**Comment by andgineer** [comment]
the problem is - it affects optimization.
so we won't see any problems at a small input text.

**Comment by Alexey-T** [comment]
I changed it and didn't see difference in test_benchmark. i won't fix it.

**Comment by andgineer** [comment]
in which commit did you changed it?

**Comment by Alexey-T** [comment]
i changed it temporary- not commited to git.

**Comment by Alexey-T** [comment]
```
        if BracesMin > 0 then
          flagp := flag_Worst; //???
        if Bracesmax > 0 then
          flagp := flagp or flag_HasWidth or flag_SpecStart;
```
so we have HasWidth set OK, because it' set by 2nd condition "if BracesMax>0".
