### ISSUE TITLE
Does not compile with Delphi 2009

### ISSUE THREAD

**Issue by dummzeuch** [andgineer/TRegExpr#139]
So far I found the following issues when trying to compile regexpr.pas with Delphi 2009:

- the unit System.Characters does not exist, it's still called Characters in that version. But the cond. define around the uses line is for Delphi 2009,
- several inline statements in the implementation do not compile. The first one is
`procedure` TRegExpr.EmitC(ch: REChar); {$IFDEF InlineFuncs}inline;{$ENDIF}`
If I move the inline to the interface declaration, it does compile.
- Several nested procedures in TRegExpr.ParseAtom cannot be inlined. If I remove the inline it compiles.
- TRegExpr.Dump does not compile:
  `Result := Result + PrintableChar(Ch) // ###0.948`
  Error: Incompatible types 'Char' and 'AnsiChar'
  I tried to solve this by declaring 'Ch' as ReChar but that failed. Also, declaring the parameter of PrintableChar as 'AnsiChar' didn't work.

**Comment by Alexey-T** [comment]
I will check this soon

**Comment by Alexey-T** [comment]
Better don’t wait for me and make your pull req.

**Comment by andgineer** [comment]
Sorry I cannot check with Delphi at the moment.
Too long to elaborate and anyway NDA but this is true - I just cannot install Delphi.
This is crazy I know..

**Comment by Alexey-T** [comment]
>     * the unit System.Characters does not exist, it's still called Characters in that version. But the cond. define around the uses line is for Delphi 2009,

I made a patch to my repo, pls test it - I dont have D2009 nor I want to download and register it.
https://github.com/alexey-t/tregexpr

**Comment by Alexey-T** [comment]
I tried to fix all others, see my repo again. Is it ok?

**Comment by andgineer** [comment]
Just to be clear - @dummzeuch please check the Alexey's repo with your Delphi.

**Comment by dummzeuch** [comment]
Yes, that version compiles fine with Delphi 2009, thanks Alexey-T. I'm going to test some other versions too.

**Comment by dummzeuch** [comment]
Actually in Delphi 2010 the unit was also still called Character, not System.Character. After changing that it compiles fine with that version too.

**Comment by dummzeuch** [comment]
Apparently the unit was renamed in Delphi XE2, so using this should be fine:

{$IFDEF FPC}
{$IFDEF UnicodeWordDetection}
uses
  UnicodeData;
{$ENDIF}
{$ELSE}
{$IFDEF D2009}
uses
  // unit exists since Delphi 2009
  {$IFDEF D_XE2}
  System.Character;
  {$ELSE}
  Character;
  {$ENDIF}
{$ENDIF}
{$ENDIF}

**Comment by Alexey-T** [comment]
Added this change, tks
