### ISSUE TITLE
regexpstudio.com no longer exists

### ISSUE THREAD

**Issue by dummzeuch** [andgineer/TRegExpr#143]
file_id.diz still refers to http://regexpstudio.com but that site apparently no longer exists (and redirects to random advertising sites.

**Comment by dummzeuch** [comment]
It's also referenced in REStudioMain.

**Comment by andgineer** [comment]
Thank you!
https://github.com/andgineer/TRegExpr/commit/78e0855363b3a3fb8567a73cb09fab20de66db07
