### ISSUE TITLE
restudio does not compile in Delphi

### ISSUE THREAD

**Issue by dummzeuch** [andgineer/TRegExpr#144]
restudio.dpr doesn't compile in Delphi (I tried XE8, but I think it won't compile in any other version either):

-  unit 'interfaces' not found
-  subdirectories persistence and StopWatch do not exist in restudio directory (they are in the main directory, so the included unit file names should be ..\StopWatch\StopWatch.pas, ..\persistence\ansoRTTIHook.pas, ..\persistence\ansoStings.pas and ..\persistence\tynlist.pas
-  regexpr is in ..\src\regexpr
- what about regexpr_compilers.inc ?

If I fix this, I get the following error in tynlist, line 341:
Left side cannot be assigned to.

initialization
  tynItemClasses := TObjectList.Create;

That means the option "Assignable typed constants" must be enabled.

Unit stopwatch also doesn't compile as it has Windows listed in the interface and the implementation uses clause.

Which Delphi Version should it compile with?

**Comment by andgineer** [comment]
It was ok very log time ago
And at the moment I cannot install Delphi on my PC (this is blocked by my company rules) so I cannot help you :((
Sorry :(

If you find the solution please share it with others - send PR, please.

**Comment by Alexey-T** [comment]
i got report about some my component bug on Delphi. and i cannot test it too.

**Comment by zrfisaac** [comment]
I didn't understand. The "restudio.dpr" file is in this project? I've searched but I didn't find.

**Comment by Alexey-T** [comment]
@andgineer Since REStudio is absent in this repo - please code the issue

**Comment by andgineer** [comment]
We removed the code
https://github.com/andgineer/TRegExpr/issues/201

It was outdated and anyway there are a lot of way better regex debuggers
