### ISSUE TITLE
Invalid regex are supported and working

### ISSUE THREAD

**Issue by SlMaker** [andgineer/TRegExpr#146]
Working regexes which should fail:
```
[._-\s]((19|20)\d{2})
[._-\s](US|UK|AU|CA|NZ)[\s._-]
```
regex101: 
> You can not create a range with a shorthand escape sequences

Shouldn't allow the **-** at that position in the regex.

**Comment by SlMaker** [comment]
@Alexey-T

**Comment by Alexey-T** [comment]
Maybe i can add the error on such case. what @andgineer thinks?

**Comment by masterandrey** [comment]
“-]” is ok this is shorthand to add “-“ in the range without backslash.
“-\s]” has no sense that should be an error. You can express that as “\s-]” or “\-\s]”

**Comment by Alexey-T** [comment]
@masterandrey agree.

**Comment by Alexey-T** [comment]
@SlMaker you are doing smth wrong
here with test.pas with
```
procedure TTestRegexpr.TestBads;
begin
  //TestBadRegex('No Error for bad braces', 'd{');
  //TestBadRegex('No Error for bad braces', 'd{22');
  //TestBadRegex('No Error for bad braces', 'd{}');
  TestBadRegex('Invalid char class after dash in []', '[._-\s]((19|20)\d{2})');
end;
```
I got FPC error
![Screenshot from 2020-05-11 01-49-10](https://user-images.githubusercontent.com/4154978/81512564-1943ba80-932a-11ea-91ec-98af2d271e5e.png)

**Comment by SlMaker** [comment]
Was accepted and working in older versions but doesn't work any more but is correct
