### ISSUE TITLE
Valid regex throws metachar after "-" in [] range

### ISSUE THREAD

**Issue by SlMaker** [andgineer/TRegExpr#147]
valid regex (see regex101):
```
[.-]
```
error:
> metachar after "-" in [] range

Worked fine in older version.

**Comment by Alexey-T** [comment]
you are doing smth wrong. CudaText works with this regex
![Screenshot from 2020-05-11 01-55-49](https://user-images.githubusercontent.com/4154978/81512662-e9e17d80-932a-11ea-8874-dd47af837782.png)

**Comment by SlMaker** [comment]
```pascal
program TRegExprTest;

{$ifdef FPC}
{$mode Delphi}
{$else}
{$APPTYPE CONSOLE}
{$endif}

uses
  SysUtils,
  RegExpr in 'TRegExpr-master\TRegExpr-master\src\RegExpr.pas';

function TestRegex(input, expr: String): boolean;
var
  rm: TRegExpr;
begin
    rm := TRegExpr.Create;
    rm.ModifierI := False;
    rm.Expression := expr;
    Result := rm.Exec(input);
end;

begin
  try
    writeln (BoolToStr(TestRegex('This.Is.A.Test.1234', '[.-](Test)[.-]'), True));
    writeln (BoolToStr(TestRegex('This.Is.A.Test.1234', '[.\-](Test)[.\-]'), True));
    writeln (BoolToStr(TestRegex('This.Is.A.Test.1234', '[\.\-](Test)[\.\-]'), True));
    readln;
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.
```
prints
```
False
True
True
```
which shows that it doesn't work.

**Comment by Alexey-T** [comment]
I am not sure how such regexes should work, sorry

**Comment by hrxcodes** [comment]
All the try cases from @SlMaker used to evaluate to `True` before

PCRE / ECMAScript / Python and GoLang implementations has all of the regexes in the try block working as I would expect and TRegExpr did evalute these to `True` before I updated the lib and there is no such regression mentioned.

## Examples
* https://regex101.com/r/gtS7Ue/1
* https://regex101.com/r/gtS7Ue/2
* https://regex101.com/r/gtS7Ue/3


## External info

Below info is copied from [this link](https://www.regular-expressions.info/charclass.html)
The hyphen can be included right after the opening bracket, or right before the closing bracket, or right after the negating caret. Both `[-x]` and `[x-]` match an x or a hyphen. `[^-x]` and `[^x-]` match any character that is not an x or a hyphen. This works in all flavors discussed in this tutorial. 

Hyphens at other positions in character classes where they can’t form a range may be interpreted as literals or as errors. Regex flavors are quite inconsistent about this

**Comment by Alexey-T** [comment]
thanks, so I must see this later.

**Comment by Alexey-T** [comment]
test my fix, please.
https://github.com/alexey-t/tregexpr

**Comment by SlMaker** [comment]
Nice thanks, works here with FPC.
Pull my requests so that it gets tested automatically in future.

**Comment by Alexey-T** [comment]
@andgineer wait, somthing is bad in my patch, other regexes broken.

**Comment by Alexey-T** [comment]
patch is ok (deleted prev comment).
