### ISSUE TITLE
Directory is missing in restudio

### ISSUE THREAD

**Issue by gitahz** [andgineer/TRegExpr#15]
I can't compile restudio due to a missing directory.

The compiler complaines about missing unit 'tynList' which is expected in directory 'Persistence'.
Unfortunally this directory does not exist.

Can you please provide the directory (with tynlist, ansoStrings & ansoRTTIHook)?

Kind regards
Andreas

**Comment by andgineer** [comment]
I added the files
https://github.com/andgineer/TRegExpr/commit/c293a023c205fb32b9a984325a33dcaa6669378b

Can you compile now?

**Comment by gitahz** [comment]
Thanks a lot :)

Works after some minor changes:
  * Moved directory Persistance to restudio/persistance
  * ansoRTTIHook.pas: PropKind := PropInfo^.PropType^^.Kind; --> PropKind := PropInfo^.PropType.Kind;
  * FileViewer.pas: dfm is missing in  repo. But the class is actually not used --> commented out.

I can try  (never done before, sorry) to make a pull request for this if you want.

Just made some basic tests and it seems to work. 
Handy tool when i need some regexes in my programs.
  
Unfortunally the "File" and "r.e. repository >>" buttons are non-functional. 
The latter seems to work only with Delphi but not with Lazarus because it was autogenerated and wants (i.e.) IXMLNodeCollection which is not available in Lazarus yet.
