### ISSUE TITLE
new tests fail

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#153]
#150 patch makes failed tests.
are these tests okay? not sure.
![Screenshot from 2020-05-17 10-22-57](https://user-images.githubusercontent.com/4154978/82138380-b02bdd80-9828-11ea-9ed5-b7f069bcde9e.png)
![Screenshot from 2020-05-17 10-23-13](https://user-images.githubusercontent.com/4154978/82138382-b326ce00-9828-11ea-8726-db7be82dce6c.png)

@SlMaker

**Comment by Alexey-T** [comment]
@andgineer are you sure that PR is ok? maybe revert it.

**Comment by SlMaker** [comment]
Maybe the code of the tests are wrong but the regex itself should work!

**Comment by SlMaker** [comment]
@Alexey-T 
could you maybe fix the tests? It's obvious what should be matched/returned.

**Comment by andgineer** [comment]
the re in the tests just wrong for any flavour of re

([.-]) you have to escape `.` if you want a dot itself and not meta-char "any symbol"
([\.-])

**Comment by SlMaker** [comment]
No.
> Match a single character present in the list below [.-]
.- matches a single character in the list .- (case sensitive)

from regex101 - all flavours.

**Comment by SlMaker** [comment]
Wrong tests fixed by #156
