### ISSUE TITLE
String contains null character not matched properly

### ISSUE THREAD

**Issue by zamronypj** [andgineer/TRegExpr#16]
NUL character does not properly matched.

```
program testemail;

uses
    regexpr;

var
  RegexObj: TRegExpr;

begin
  RegexObj := TRegExpr.Create;

  regexObj.expression := '^(\d+):CONTENT_LENGTH\x00(\d+)\x00';
  if RegexObj.Exec('1065:CONTENT_LENGTH' + #0 + '185364' + #0 + 'SCGI'+ #0 + '1' + #0 + 'CONTENT_') then 
      WriteLn('matched!');
  RegexObj.Free;
end.
```

**Comment by andgineer** [comment]
You are absolutely right.
Inside TRegExpr I use PChars to process strings. This is #0-terminated sequences, so TRegExpr just cannot process strings with #0 inside strings.

If you want you can improve that.
Just have to warn you that will take a lot of work.

**Comment by andgineer** [comment]
I wrote about that in the FAQ
https://github.com/andgineer/TRegExpr/commit/820858bc6581125c7909b4a432d68d3f275dda41
https://regex.sorokin.engineer/en/latest/faq.html#why-tregexpr-does-not-work-with-strings-with-0-inside
