### ISSUE TITLE
[.] without escaping should be metachar and not just dot itself

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#160]
@andgineer 
@SlMaker - your opinion? I can fix. if you find info about other engines

**Comment by SlMaker** [comment]
on https://regex101.com/r/qr9Zbh/1 `[.]` matches only the dot for all flavours

**Comment by Alexey-T** [comment]
@andgineer So maybe leave code as is? its now as in all flavors?

**Comment by masterandrey** [comment]
Ok.. but strange anyway - [\w] works as expected - any word letter..

**Comment by Alexey-T** [comment]
because of my adddions - I added that \w \d \W \D work in [ ].

**Comment by SlMaker** [comment]
So nothing needs to be changed?

**Comment by Alexey-T** [comment]
yes

**Comment by Alexey-T** [comment]
@andgineer closing it?

**Comment by andgineer** [comment]
https://regex.sorokin.engineer/en/latest/regular_expressions.html#predefined-character-classes
> You may use \w, \d and \s within user character classes.

yes - I even documented that by your request but forget that ;)

**Comment by Alexey-T** [comment]
Forget-forgot-forgotten
:)
