### ISSUE TITLE
Source of TRegExpr for fpc.

### ISSUE THREAD

**Issue by fredvs** [andgineer/TRegExpr#162]
Hello.

In attachment, source for the fpc compiler.
Tested with last fpc 3.2.0 fixes.

[fpc_packages_regexpr_src.zip](https://github.com/andgineer/TRegExpr/files/4671651/fpc_packages_regexpr_src.zip)

(I hope this one is ok)

**Comment by Alexey-T** [comment]
I already use trunk with FPC 3.3 and 3.2. what 's new?

**Comment by fredvs** [comment]
> I already use trunk with FPC 3.3 and 3.2. what 's new?

Sorry, I did not understand.
What 's new in what?

**Comment by fredvs** [comment]
Maybe we misunderstood.

I have done the patch using your code and have test it.
Of course there is nothing new, it is your code but ready to use for fpc compiler source.

**Comment by Alexey-T** [comment]
so it's patch for FPC code base. please post this to FreePascal bugtracker, they dont read here.

**Comment by fredvs** [comment]
They never take care of my patches in FreePascal bugtracker, so sorry but I dont give them patches anymore.
It is the reason I give it to you in case if you want to compile your own fpc.

**Comment by Alexey-T** [comment]
looked at fpc-ootb.

- better name binaries not so cryptic. linux-x32, linux-x64, linux-arm, linux-aarch64 (or -arm64, its the same). win-x32, win-x64.

**Comment by fredvs** [comment]
>better name binaries not so cryptic. linux-x32, linux-x64, linux-arm, linux-aarch64 (or -arm64, its 


From Stackoverflow:


> armhf stands for "arm hard float", and is the name given to a Debian port for arm processors (armv7+) that have hardware floating point support.
> The cpu of the Raspberry is 64 bit but at the moment, Raspbian OS is still 32 bit.


So you may see it is not easy to choose the right name!
But ok, for next release I will change it.


> good to have - win-arm64 (64! because MS Surface Pro X has ARM64 CPU)


If you refer to StackOverflow, all cpu armhf (so the one of Raspberry pi too) are 64 bit.
It is the OS Raspbian stable that is still 32 bit (but there is a Raspbian 64 nearly ready).

But I never try Windows for arm64.
Did you try it?
Whas it easy to install?


Afaik, aarch64

**Comment by Alexey-T** [comment]
arm64 is synonim for AArch64. see wikipedia.
Win10 exists for arm64. 
https://www.microsoft.com/en-us/p/surface-pro-x/8vdnrp2m6hhc?activetab=overview

Win10 for arm64 will be released in ISO

**Comment by fredvs** [comment]
Hum, I did some research about fpc + arm64 and it is for from working yet.

By the way if you have a Surface Pro, I will highly interested to help you to do a win-arm64 release.

Sadly, all what I found about test of Win10 on Rpi 4 are not very positive.
Yes, it is possible to install it but running application is extremely slow and I fear that using my Rpi to compile fpc will take centuries.

**Comment by Alexey-T** [comment]
but I dont have Surface..

**Comment by fredvs** [comment]
OK but I dont know anybody that has one.
