### ISSUE TITLE
Filename doesn't match unit

### ISSUE THREAD

**Issue by SlMaker** [andgineer/TRegExpr#171]
regexpr_unicodedata.pas file vs `unit RegExpr_UnicodeData;` and `uses
  RegExpr_UnicodeData;`

**Comment by Alexey-T** [comment]
it dont make problem for FPC, because FPC finds lower case filename. (on Linux)

**Comment by SlMaker** [comment]
But it will use any other file if it matches the case as the lowercase is not highest priority (just a fallback method afaik)

**Comment by SlMaker** [comment]
Same applied for the unit name change from `regexpr.pas` to `RegExpr.pas` where it used the FPC version of TRegExpr as my `uses` list still had `regexpr` even if provided the path to this library via `-Fu`.

**Comment by Alexey-T** [comment]
what do you suggest? to lower-case name in "unit nnnnnn" line?

**Comment by andgineer** [comment]
I would suggest to use the same names in files and in uses.
What are the naming convention for that now?

This names are 20+ years old. At the moment I considered them as more readable.
But may be for now fpc have strict naming convention?

For JAVA this is ClassName for the class and the file.
For Python ClassName for the class and class_name for the file..

**Comment by Alexey-T** [comment]
Ok, doing mass-replace, making PullReq.
![Screenshot from 2020-06-29 10-45-23](https://user-images.githubusercontent.com/4154978/85987090-d9c65000-b9f5-11ea-8244-7c6d21f685b2.png)

it is plugin FindInFiles in CudaText
@kvichans

**Comment by Alexey-T** [comment]
solved in #170 ?
