### ISSUE TITLE
Simple quantifier fails on input string of '..'

### ISSUE THREAD

**Issue by astr0wiz** [andgineer/TRegExpr#181]
I used this code to test:

```
Procedure TGenForm.OKButtonClick(Sender: TObject);
  Var
    searchInfo: TSearchRec;
    isEmpty:    boolean;
    rx:         TRegExpr;
    check1,check2: boolean;
  Begin
    rx      := TRegExpr.Create('^\.{1,2}$');
    isEmpty := True;
      Try
      If FindFirst(IncludeTrailingPathDelimiter(DirLocation.Caption) + '*', faDirectory, searchInfo) = 0 Then
        Repeat
          check1:=ExecRegExpr('^\.|\.\.$',searchInfo.Name);
          check2:=ExecRegExpr('^\.{1,2}$',searchInfo.Name);
          isEmpty:= rx.Exec(searchInfo.Name);
        Until Not isEmpty Or (FindNext(searchInfo) <> 0);
      Finally
      FindClose(searchInfo);
      rx.Free;
      End;
    If isEmpty Then
      ShowMessage('ok')
    Else
      ShowMessage('Warning:  Directory is not empty!');
  End;
```
I set a breakpoint on the Until statement.  When the file name is '.', all booleans return True.  However, when the input string is '..', check1 is True, but check2 is false.

Problem:  The two regular expressions are essentially the same, but the quantifier fails on its test against '..'.

I am using Lazarus 2.0.10 with FPC v 3.2.0
TRegExpr version: 0.987

**Comment by Alexey-T** [comment]
'^\.|\.\.$'
Better close dots to brackets, I am not sure how | works here

**Comment by Alexey-T** [comment]
good thing - I dont reproduce this in CudaText (TRegExpr version 1.100) on such text file
```
.
..
...
.
..
.....
.
```
it finds OK lines.

**Comment by Alexey-T** [comment]
@andgineer It was fixed already, pls close.

**Comment by andgineer** [comment]
@Alexey-T could you add here commit id?

**Comment by Alexey-T** [comment]
https://github.com/andgineer/TRegExpr/commit/544569e7419c7a94f1c7f8dd642697136d468705

Issue #145
