### ISSUE TITLE
Supported unicode categories \p \P

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#184]
Docs
http://www.regular-expressions.info/unicode.html#prop

List of categories
https://www.compart.com/en/unicode/category/

Tests by Dialog demo
![Screenshot from 2020-08-18 23-47-11](https://user-images.githubusercontent.com/4154978/90564090-706ced00-e1ad-11ea-9be3-ded92b99c057.png)

in pull-request.
@kvichans @SlMaker  @dinkumoil

**Comment by kvichans** [comment]
Намекните хоть о чем тут речь. Главное, чтобы новые фишки не изменяли работу старых.
Если пойму новые фишки, попробую их применять

**Comment by Alexey-T** [comment]
https://stackoverflow.com/questions/14891129/regular-expression-pl-and-pn

поиск символов для "категории". L- буква, Lu- uppercase буква...
