### ISSUE TITLE
Minor change to make little faster

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#185]
@andgineer I suggest to lower (move down) the checks for \v \V \h \H in "case" blocks in all places, to little speedup case blocks. \v \h are rarely used. OK?

**Comment by andgineer** [comment]
That's ok for me.
Too bad this is sequential in any case - better it be hashed :(

**Comment by Alexey-T** [comment]
Maybe I can make array[char] of <func>. will see.
