### ISSUE TITLE
Move 'Persistence' to another repo

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#201]
This dir in repo has not related project. Ie some lib and anso* units. Pls move to another repo?

**Comment by andgineer** [comment]
of cause.
we do not need that inside TRegExpr

**Comment by Alexey-T** [comment]
Thanks. I will close when you move it.

**Comment by andgineer** [comment]
19886dbb2763ba87acb7eba57925967b21f172da
