### ISSUE TITLE
Wanted features of RegEx in FreePascal

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#21]
Big thanks for your RegExpr unit in FPC. It's very useful!
User of CudaText program wants modern regex features, he listed them in this page:
https://github.com/Alexey-T/CudaText/issues/2279

What do you think?

**Comment by andgineer** [comment]
Thank you for your PR.
Sorry for late answer.
You see I wrote the library 20 years ago and now I have not code in Pascal for 10 years..
