### ISSUE TITLE
make a release

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#230]
Pls make a 'release' in GH. old one is too old.

**Comment by Alexey-T** [comment]
@andgineer ?

**Comment by andgineer** [comment]
Hm may be just delete old 'releases'?

I created them to place somehow old binary hlp-files.
So if you do not need to distribute binary files what's the point to have 'releases'?

**Comment by Alexey-T** [comment]
We have this GH feature, lets use it.

**Comment by andgineer** [comment]
Ok, sure.
Release are for delivering binaries.

Lets compile some binaries.. Any ideas which ones?

**Comment by Alexey-T** [comment]
nope, you just go  to "Releases" part of GH, press there button, and all done- GH makes zip file.

**Comment by andgineer** [comment]
Sure.
But what's the point?
Even if we had release flow (and we have not) better to mark stable releases with git tags.
Why do we need binary releases?

**Comment by Alexey-T** [comment]
It is binary? GH release is just a tag, with current source in zip file...

**Comment by andgineer** [comment]
Ok, zip file wit sources.
What for somebody will need it?
And why we realease now - we have some release flow that say us - now we have stable version?
If so why not just git tag it?

**Comment by Alexey-T** [comment]
Is it the same as git tag, only simpler to do - via web.
