### ISSUE TITLE
Compilation error with Delphi 10.3

### ISSUE THREAD

**Issue by SlMaker** [andgineer/TRegExpr#234]
Compiling fails with Delphi 10.3:
```c
regexpr.pas(2287) Error: E2441 Inline function declared in interface section must not use local symbol 'OP_BSUBEXPCI'
regexpr.pas(2289) Error: E2441 Inline function declared in interface section must not use local symbol 'OP_BSUBEXP'
```

**Comment by Alexey-T** [comment]
try to delete "inline;" for that function. it's compiled then? give the patch.

**Comment by Alexey-T** [comment]
ie try to delete "inline" line here
```
    // emit back-reference to group
    function EmitGroupRef(AIndex: integer; AIgnoreCase: boolean): PRegExprChar;
      {$IFDEF InlineFuncs}inline;{$ENDIF}
```

**Comment by SlMaker** [comment]
This alone does not fix it.  
New error is raised for `procedure FindSubstGroupIndex`, this inline also needs to be removed

**Comment by SlMaker** [comment]
Think it's the same problem as in #233 just with a different solution by removing the inline command

**Comment by Alexey-T** [comment]
you need to make the patch by urself. I don't have Delphi 10.3 (license was lost?) and newer Delphi.
i suggest to make additional define InlineDx

{$ifdef InlineFuncs}
{$ifdef FPC}
  {$define InlineFP}
{$endif}
{$endif}

then change {$ifdef InlineFuncs} to new word. in all needeed places in interface funcs which give error.

**Comment by SlMaker** [comment]
Better remove the inline completely as inline command is discouraged by FPC devs anyway. And they also say FPC is not as strict as it should be so it could stop working any time.

**Comment by SlMaker** [comment]
#235

**Comment by Alexey-T** [comment]
patch looks ok.

**Comment by Alexey-T** [comment]
@andgineer please close.
