### ISSUE TITLE
Throws error for correct regex: unknown meta-character

### ISSUE THREAD

**Issue by SlMaker** [andgineer/TRegExpr#236]
regex:
> `[\.\-\_](\w+)[\.\-\_]`

error message:
> unknown meta-character: \_ (pos 6)

it's a valid regex and matched by all engines: https://regex101.com/r/v74T2Y/1

**Comment by SlMaker** [comment]
@Alexey-T

**Comment by SlMaker** [comment]
Maybe add this regex also to the testcases

**Comment by Alexey-T** [comment]
what other chars must be handled ok here? besides of `_`. let's collect them, for my fix.

**Comment by SlMaker** [comment]
> The usual metacharacters are `{}[]()^$.|*+?` and `\.`
> The usual characters that become metacharacters when escaped are `dswDSW` and `N`

https://en.wikipedia.org/wiki/Regular_expression#Syntax

**Comment by SlMaker** [comment]
Looks like you can escape every character and as long as it doesn't have a regex meaning it works fine

`(\q)` matches
```
qq_qq-qq
qq12qq
```
see https://regex101.com/r/slGUfp/1

**Comment by Alexey-T** [comment]
okay; I will make the fix.

**Comment by Alexey-T** [comment]
@andgineer pls apply the PR. I didnt allow other word-chars to be escaped. its possible hole: e.g. \q - better show that it's an error.

**Comment by SlMaker** [comment]
thanks
Maybe add some test cases for this to be sure it never get broken again?

**Comment by Alexey-T** [comment]
doesnt worth it; i tested it in the dialog-demo.

**Comment by andgineer** [comment]
Are we sure that will do better than before?

For me better to let escape any "suspicious" symbol. And I do not want to remember is this symbol have any special meaning in this version of regex.

Like "\.\,". So If I want just symbol "," I will escape it and I do not want to remember if "," has any special role. I just want to be sure in this case it will be just ",". So I add "\" without any research if I really have to do that.

And what the harm if "\q" will be treated as plain "q"?

**Comment by Alexey-T** [comment]
IMO its ok to show errors for \q (all unknown letters). users never write \q meaning "q", but yes they write \. \, \~ \% \@ for symbol chars.
