### ISSUE TITLE
regression: regexpression ignores changes to modifier

### ISSUE THREAD

**Issue by User4martin** [andgineer/TRegExpr#238]
See https://bugs.freepascal.org/view.php?id=38442

**Comment by Alexey-T** [comment]
It is easy to fix, pls wait.

**Comment by User4martin** [comment]
IMHO the fix is not ideal.

It may be unlikely, but if a user changes a modifier and reverts the change before the next match, then the program still recompiles.

But it is ok for me.

**Comment by Alexey-T** [comment]
The other way- changing in MatchPrim, is bad- MatchPrim is called NNN times in tests (maybe it can be recursive? forgot)

**Comment by User4martin** [comment]
Ok
