### ISSUE TITLE
Please fix restudio

### ISSUE THREAD

**Issue by mvancanneyt** [andgineer/TRegExpr#240]
ReStudio does not compile anymore under delphi. 
Suggest fixing it or removing it.

When you fix it, also fix the working itself.
The logic of regex changed, so ExecIt must be adapted:

procedure TfmREDebuggerMain.ExecIt (AFindNext : boolean);

    if not aFindNext then
      begin
      r.Expression := edRegExpr.Text;
      {$IFDEF UseProfiler}
      sw.Start;
      {$ENDIF}
      ProtectedCompilation;
      {$IFDEF UseProfiler}
      sw.Stop;
      lblStopWatch.Caption := 'Compile: ' + sw.TimeStr;
      {$ENDIF}
      end;

With the above change, I managed to get it to work again.
I took many shortcuts: simply remove references to missing files such as fileviewer form, stopwatch which no longer works, so I will not provide a patch. But you can get it to work.

**Comment by Alexey-T** [comment]
@andgineer Ping...

**Comment by Alexey-T** [comment]
Ops, REStudio is abset in this repo now? I cannot see it. then close the issue.

**Comment by andgineer** [comment]
We removed the code
https://github.com/andgineer/TRegExpr/issues/201

It was outdated and anyway there are a lot of way better regex debuggers
