### ISSUE TITLE
compiling errors on Delphi 2010

### ISSUE THREAD

**Issue by mirkasp** [andgineer/TRegExpr#244]
Hi,
There are errors when compiling on Delphi 2010:

[DCC Fatal Error] regexpr.pas(116): F1026 File not found: 'System.Character.dcu'
and
[DCC Error] regexpr.pas(859): E2441 Inline function declared in interface section must not use local symbol 'PtrPair'

Best regards
MirKasp

**Comment by Alexey-T** [comment]
Is unit System.Character in D2010? 
http://docwiki.embarcadero.com/RADStudio/Sydney/en/Character_Manipulation_Routines

it is in D 10.4.
in what D did this unit appear?

**Comment by mirkasp** [comment]
Yes,  but without prefix "System." - only "Character.pas" 
Only two files have a prefix: "Generics.Collections.pas" and "Generics.Defaults.pas". 
All other source files have single-member names, for example: StrUtils.pas, Classes.pas, AnsiStrings.pas, etc.

**Comment by Alexey-T** [comment]
Can you make the easy fix, and post your Pull req? I dont have Delph now.

**Comment by andgineer** [comment]
@mirkasp Is the problem solved?
could you please close the ticket?

**Comment by mirkasp** [comment]
Yes, it's work !
