### ISSUE TITLE
Substitute fails when using named references

### ISSUE THREAD

**Issue by chrisgch** [andgineer/TRegExpr#247]
A call to
function TRegExpr.Substitute(const ATemplate: RegExprString): RegExprString;
fails with error reeNamedGroupBad when the template contains named references like ${name} defined in the regular expression via (?P<name>expression) or (?'name'expression)

**Reason:**
Substitute calls FindGroupName (within subfunction ParseVarName), and FindGroupName contains this check:
if P >= fRegexEnd then
      Error(reeNamedGroupBad);
However, this only works when FindGroupName is called from TRegExpr.ParseAtom, where FindGroupName searches for group names within the regular expression. But when FindGroupName is called from Substitute, it has to search for group names within the ATemplate string, so the above check compares with the wrong end pointer.

**Suggested fix:**
1. Change FindGroupName to the following definition:
procedure TRegExpr.FindGroupName(APtr, AEndPtr: PRegExprChar; AEndChar: REChar; var AName: RegExprString);
2. Change
if P >= fRegexEnd then
to
if P >= AEndPtr then
3. Change all calls to FindGroupName within ParseAtom to FindGroupName(... , fRegexEnd, ...
4. Change all calls to FindGroupName within Substitute to FindGroupName(... , TemplateEnd, ...

**Comment by Alexey-T** [comment]
done as you suggested. thanks for help!
will do the pull-req now. work is in https://github.com/Alexey-T/TRegExpr

**Comment by chrisgch** [comment]
Thanks, that's exactly what I meant. Your changes fix the problem.
