### ISSUE TITLE
No match for an empty string

### ISSUE THREAD

**Issue by NoAnyName** [andgineer/TRegExpr#249]
Hello!

I have happened to notice that TRegExpr doesn't work with empty input strings anymore.
RegExp's like "^$" or "^ *$" are perfectly valid patterns and should match an empty string in first case and empty or string of spaces in second. However, due to the check
```
  if fInputString = '' then
  begin
    //Error(reeNoInputStringSpecified); // better don't raise error, breaks some apps
    Exit;
  end;

```
empty string isn't welcome.

In older versions, it used to check for pchar pointer, which worked fine, because empty string would still have a valid pointer, leading to "\0":
```
  if not Assigned (fInputString) then begin
    Error (reeNoInpitStringSpecified);
    EXIT;
   end;
```

This change in behaviour breaks some regexps :) Just removing the check for an empty string seems to fix it, but I'm not sure it won't backfire somewhere deep in the code.

**Comment by Alexey-T** [comment]
fixed in my fork, patch is linked above this comment.

**Comment by NoAnyName** [comment]
Thank you!
