### ISSUE TITLE
Maybe delete this getter?

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#25]
```
function TRegExpr.GetInputString : RegExprString;
 begin
  if fInputString = '' then begin
    Error (reeGetInputStringWithoutInputString);
    EXIT;
   end;
  Result := fInputString;
 end; { of function TRegExpr.GetInputString
```
Ok to remove getter, or it's needed?

**Comment by andgineer** [comment]
My Pascal is a little rusty but don't we need it to .InputString work as property?

**Comment by Alexey-T** [comment]
Property will work anyway, it will be declared as 

Property InputString: ..... read fInputString write SetInputString

Here getter GetInputString replaced with var fInputString, so user don’t call checks in GetInputString (which shows exception in it).

**Comment by andgineer** [comment]
ups silly me..
of cause we do not need this getter if there are no checks..

**Comment by Alexey-T** [comment]
This getter has one check, do we need it?
```
function TRegExpr.GetInputString : RegExprString;
 begin
  if fInputString = '' then begin
    Error (reeGetInputStringWithoutInputString);
    EXIT;
   end;
  Result := fInputString;
 end; { of function TRegExpr.GetInputString
```

**Comment by andgineer** [comment]
I this is my mistake - I better use the property inside TRegExpr so to return clear error message if a library user call something that use input string but forget to assign it first..
But I forget to use the property and use inside TRegExpr just fInternalString so that just does not work

**Comment by Alexey-T** [comment]
Ok, se I will remove the getter (after you apply my patch)
