### ISSUE TITLE
Compile problems with delphi 7

### ISSUE THREAD

**Issue by HPWi** [andgineer/TRegExpr#252]
Hello,

Trying to compile with delphi 7 without success:

function TRegExpr.DumpCheckerIndex(N: byte): RegExprString;
begin
  Result := '?';
  if N = CheckerIndex_Word then Exit('\w');
...
...

Exit with parameters not supported by D7-
Changed to:  if N = CheckerIndex_Word then Result := '\w';

function TRegExpr.DumpCategoryChars(ch, ch2: REChar; Positive: boolean): RegExprString;
const
  S: array[boolean] of REChar = ('P', 'p');
begin
  Result := '\' + S[Positive] + '{' + ch;

S[Positive] produce an error about type mismatch. What to do?

Regards
Hans-Peter

**Comment by HPWi** [comment]
As a workaround I changed to:

function TRegExpr.DumpCategoryChars(ch, ch2: REChar; Positive: boolean): RegExprString;
begin
  if Positive then
   Result := '\' + 'P' + '{' + ch
  else
   Result := '\' + 'p' + '{' + ch;

Now it compiles. ;-)

**Comment by Alexey-T** [comment]
Fixed in my fork. https://github.com/Alexey-T/tregexpr
