### ISSUE TITLE
Проблема при распознавании киррилических символов

### ISSUE THREAD

**Issue by iLya2IK** [andgineer/TRegExpr#258]
Данный код выдает некорректные результаты (выдает 3 совпадения: 'мо?', 'о?' и 'ка', должно выдавать один результат: 'морошка').
```
  re := TRegExpr.Create('(([а-я]+)|([a-z]+)|(\d+))');
  re.ModifierR := true;
  try
    if re.Exec('морошка') then
      repeat
        Add(re.Match[0]);
      until not re.ExecNext;
  finally
    re.Free;
  end; 
```
Предполагаю, что проблемы возникают при распознавании символов из utf8-диапазона с префиксом 0xd1 ('р'-'я'), поскольку при замене первой строки на
```
re := TRegExpr.Create('(([а-пр-я]+)|([a-z]+)|(\d+))'); 
```
результаты получаются ожидаемыми

**Comment by Alexey-T** [comment]
Т к при добавлении теста в test_fpc проект я получаю ошибку вида
![Screenshot from 2021-09-27 12-56-51](https://user-images.githubusercontent.com/4154978/134887442-c0c06b9e-1ba1-41d1-a682-3d3e0564f715.png)

то есть порченый текст, я подозреваю некоректную кодировку "морошка" еще ДО передачи в код парсера. где-то не хватает utfencode/decode.

**Comment by Alexey-T** [comment]
Так и есть- проблемы в тесте, в вашем коде добавьте где надо UTF8Decode/Encode. я добавил в FPC тестер - тест, и написал его не как часть массива а специальным кодом, и работает.
https://github.com/alexey-T/tregexpr

**Comment by iLya2IK** [comment]
Проблема в устаревшей версии regexp (0.987), которая идет в комплекте с lazarus 2.0.12. В текущей версии, скаченной с github, ошибку воспроизвести не смог.
