### ISSUE TITLE
Allow NULL chars in string

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#26]
I can make a patch to allow subj, for this I want to add method InBuffer which checks for offset is it in the buffer. Okay?

**Comment by andgineer** [comment]
For the moment it is not clear for me how you are going to solve the problem.
But you see 20 years ago I kept functions call at min so the code would be faster.

BTW you non-capturing group patch does add some additional calls and loops (to get capturing group by Idx from full groups list) and I am afraid that already slow down TRegExpr a bit..

May be we need some performance tests as well so we could see clearly that we do not sacrifice performance by new patches?

**Comment by Alexey-T** [comment]
I can do optimization of GetSubExprArrayIndex

- make it "inline" (will be no function call)
- add variable NonCaptureExists:bool, which is set when first non-capture group is found, flag is checked in function to work faster

**Comment by andgineer** [comment]
You that sounds(!) good but with modern CPU - multi-levels cache, branch predictions and so on I do not believe this is possible to understand what is good for performance just theoretically.
If we had some performance tests - easy to run and to compare change. Even as CI - so if we drop performance significantly they will be red.

And only with such a tests we could understand if we really need that..

**Comment by Alexey-T** [comment]
solved
