### ISSUE TITLE
Docs: "negative lookahead assertion" instead of "negative lookbehind assertion"

### ISSUE THREAD

**Issue by Skif-off** [andgineer/TRegExpr#263]
Здесь https://regex.sorokin.engineer/ru/latest/regular_expressions.html#assertions в четвёртой строке должно быть описание отрицательного заглядывания назад, но на деле копия второй строки, с отрицательным заглядыванием вперёд. (В английской версии нормально.)

P.S. Мыло [отсюда](https://github.com/andgineer/TRegExpr/blob/master/LICENSE.txt) не работает или я неудачник?

**Comment by andgineer** [comment]
Well in all this turmoil I forget to pay for the domain beforehand and now it will expire in this May if I won't find some way to pay.
The domain and my site still working but MX forwarding do not working for some reason.
I'd sent test email and got no bounce but no forwarded email either.
 At the moment there are so many potential reasons for that so no point even to start looking into that, at least now.
 
 Thank you for your feedback about the doc's error.

**Comment by andgineer** [comment]
https://github.com/andgineer/TRegExpr/commit/9eb76ce17f4f0cebd1237b847879efab24b24eb3

**Comment by Skif-off** [comment]
Also:
https://regex.sorokin.engineer/en/latest/#quick-start
https://regex.sorokin.engineer/ru/latest/#quick-start
link to the source is incorrect (browser shows page 404):
`https://github.com/andgineer/TRegExpr/blob/master/src/RegExpr.pas`
instead of
`https://github.com/andgineer/TRegExpr/blob/master/src/regexpr.pas`
Strange, usually links are case insensitive.

About

> Well email forwarding does work now - I'd got my test email.

```
Reporting-MTA: dns; forward400j.mail.yandex.net
X-Yandex-Queue-ID: xxxxxxxxxxx
X-Yandex-Sender: rfc822; [xxx@yandex.ru](mailto:xxx@yandex.ru)
Arrival-Date: Tue, 8 Mar 2022 06:29:02 +0300 (MSK)

Final-Recipient: rfc822; [andrey@sorokin.engineer](mailto:andrey@sorokin.engineer)
Original-Recipient: rfc822;[andrey@sorokin.engineer](mailto:andrey@sorokin.engineer)
Action: failed
Status: 4.4.1
Diagnostic-Code: X-Yandex; connect to mx1.emailowl.com[107.170.11.17]:25:
    Connection timed out
```
