### ISSUE TITLE
zero-length match not found at the end of searched string

### ISSUE THREAD

**Issue by white-gthb** [andgineer/TRegExpr#265]
Unlike in earlier versions, TRegExpr in certain cases no longer matches an zero-length match at the end of a string.
Apparently some optimization was done to TRegExpr constituting to new behavior which I consider to be a bug. 

Examples of effected regular expressions:
```
(?:)
(_[a-zA-Z]+_)?
.*\b
Q{0,5}
```

How this works out and where I first reported this can be read here:
https://www.ghisler.ch/board/viewtopic.php?t=76139

In any case, this new behavior is not consistent with older versions of TRegExpr and seemingly all other regular expression engines.

**Comment by Alexey-T** [comment]
Regex was shown. thanks. but what is the 'subject string'?
what is the position which is found by other engines?

**Comment by white-gthb** [comment]
Subject string basically can be any string.
The position found by earlier versions of TRegExp and other engines is at the end of the string.
Some examples are given in the mentioned thread on the official forum of Total Commander.

**Comment by Alexey-T** [comment]
I tried 2 first examples from TC forum

1.
```
Filename:		12345

Search for:		(?:)
Replace with:		-
1x:			Disabled
Subst:			Disabled

Result:			-1-2-3-4-5
Expected result:	-1-2-3-4-5-
```

executed replace in CudaText (it uses this engine).
result is OK!

![Screenshot from 2022-04-25 15-08-51](https://user-images.githubusercontent.com/4154978/165086136-2af910f8-d57e-4cb8-ab0b-d0d57985d05e.png)


2.
```
Filename:		1234_text_ABCD

Search for:		(_[a-zA-Z]+_)?
Replace with:		__
1x:			Disabled
Subst:			Disabled

Result:			__1__2__3__4____A__B__C__D
Expected result:	__1__2__3__4____A__B__C__D__
```

executed in CudaText. OK again!
![Screenshot from 2022-04-25 15-08-26](https://user-images.githubusercontent.com/4154978/165086071-1a91a6c4-fc5f-4318-bc39-53c58a03db26.png)

**Comment by Alexey-T** [comment]
make sure that TCmd uses the LAST version if TRegexpr.

**Comment by white-gthb** [comment]
Thanks for testing! I will notify the author.

**Comment by white-gthb** [comment]
Author says latest trunk code seems to work.

**Comment by Alexey-T** [comment]
so you can close this issue.

**Comment by Alexey-T** [comment]
@andgineer Author of TC said that 'regexpr last release is from 2017' so he took that old code. Can you make the Github release?

**Comment by andgineer** [comment]
Ok I am not sure what for but I created the release
https://github.com/andgineer/TRegExpr/releases/tag/1.155

**Comment by Alexey-T** [comment]
Thanks
