### ISSUE TITLE
Substitute: Numbered group in template defaults to "$"

### ISSUE THREAD

**Issue by white-gthb** [andgineer/TRegExpr#268]
Regression bug (it has worked in the past).
If a numbered group in the template does not exist in the regular expression, it is replaced with "$".
Example:
```
Search text:  abc
RegEx:        (b)
Template:     $1$2

Result:       ab$c
Expected:     abc
```

**Comment by Alexey-T** [comment]
I will see it soon.

**Comment by Alexey-T** [comment]
fixed in my fork! Pls test. Made a pull-req.

**Comment by white-gthb** [comment]
I don't have a developers environment set up. If you want me to test pls provide Windows binary, for example CudaText binary.

**Comment by white-gthb** [comment]
Author of Total Commander says: Fix seems to work. See:
https://www.ghisler.ch/board/viewtopic.php?p=412927#p412927

**Comment by Alexey-T** [comment]
great!
