### ISSUE TITLE
Recursive inclusion (?R) with backreferences produces wrong matches

### ISSUE THREAD

**Issue by CaptainFlint** [andgineer/TRegExpr#273]
Consider the following expression:
`([a-z])(?R)?\1`
It should find arbitrary string followed by the same string reversed, like `abccba` or `zzxxzz`. However, it does not work. Here is the contents of the test file (6 lines):
```
tesbbbb123
tesbbb123
abc_dabcd
abc_cba
aaazzz
abccba
```
I'm using Total Commander file manager which uses TRegExpr for regular expression search and replace functions. When I open this file for viewing and try to search text using the regexp given above, the following substrings are matched, successively:

line 1: `tesbbb`
line 2: `sbbb`
line 3: [no match]
line 4: [no match]
line 5: [two successive matches] `aa` + `azzz`
line 6: `abcc`

But none of these results (apart from `aa`) fits the expression.

The backreferences in recursive expressions are a bit of a grey territory, but the Perl documentation says this:

> `(?PARNO)` `(?-PARNO)` `(?+PARNO)` `(?R)` `(?0)`
> Recursive subpattern. Treat the contents of a given capture buffer in the current pattern as an independent subpattern and attempt to match it at the current position in the string. Information about capture state from the caller for things like backreferences is available to the subpattern, but capture buffers set by the subpattern are not visible to the caller.

To me it sounds as if it works like recursive functions: the local context (in this case, backreferences, which can be considered "local variables") is stored separately inside each call, and they don't affect each other, even if the variables have the same "names" (backrefrerence ID). So, if you "unfold" the expression, for example, 3 times and stop, the full expression would look like:
([a-z])<sub>a</sub>([a-z])<sub>b</sub>([a-z])<sub>c</sub>\1<sub>c</sub>\1<sub>b</sub>\1<sub>a</sub>
where subscripts show the "context", and each `\1` sits in a different context and contains a different value within its own sub-expression.

However, even if you ignore the context and consider all `\1`'s identical and residing on the global visibility level, still the matched results don't fit. For example, `tesbbb` was found, but `\1` should contain `t`, and the string must end with `ttt`, which is clearly not the case. So however you interpret this, the result does not seem right.

For reference, I tested the same expression on the same test data in Perl, and the results confirmed my original interpretation:

line 1: `bbbb`
line 2: `bb`
line 3: [no match]
line 4: [no match]
line 5: `aa`
line 6: `abccba`

The test application is: Total Commander 10.00 and 10.50 beta 5; it uses TRegExpr version: REVersionMajor = 1, REVersionMinor = 155.

**Comment by Alexey-T** [comment]
Thanks for such detailed report.
I will study this soon, maybe next week.

our current file 'test/tests.pas' has these tests for ?R, they work.
```
    // 58, recursion
    (
    expression: 'a(?R)?b';
    inputText: '__aaaabbbbbbbb__';
    substitutionText: '';
    expectedResult: 'aaaabbbb';
    matchStart: 3
    ),
    // 59, recursion, generic regex 1 - https://regular-expressions.mobi/recurse.html?wlr=1
    (
    expression: 'b(?:m|(?R))*e';
    inputText: '_bbfee_bbbmeee__';
    substitutionText: '';
    expectedResult: 'bbbmeee';
    matchStart: 8
    ),
    // 60, recursion, generic regex 2 - https://regular-expressions.mobi/recurse.html?wlr=1
    (
    expression: 'b(?R)*e|m';
    inputText: '__bbbmeee__bme__m__';
    substitutionText: '@';
    expectedResult: '__@__@__@__';
    matchStart: 1
    ),
```

**Comment by CaptainFlint** [comment]
Indeed, with static sub-expressions it works fine (as far as I could see). I noticed the problems only when I tried with backreferences.

**Comment by CudaText-addons** [comment]
your 6 lines file. in CudaText . with fixes.
![Screenshot from 2022-05-30 17-01-23](https://user-images.githubusercontent.com/17549064/171008117-8ed58508-bcf6-457a-8a34-1fab77abe74e.png)

BTW, Constantin, welcome to use CudaText and give reports :)

**Comment by CaptainFlint** [comment]
Hi, and thanks for your input! I hope it helps Andrey to nail it in the main project.

As for the editor, sorry, I prefer EmEditor, it better fits my use-cases and habits. But I'll keep in mind that I can use CudaText for such tests (and I do use CudaLister in TC :-) ).

**Comment by Alexey-T** [comment]
Andrey is not active anymore. only me.

**Comment by Alexey-T** [comment]
You can test the CudaText beta with this new code
and not wait for the TCmd update.
http://uvviewsoft.com/c/

**Comment by Alexey-T** [comment]
@CaptainFlint if you checked and it’s ok, close your issues.

**Comment by CaptainFlint** [comment]
Sorry, I haven't yet, I'm quite overloaded these days. But I will.

**Comment by CaptainFlint** [comment]
The new beta version of Total Commander has this fix. I tested there, and it seems that it works fine.
Thank you very much!
