### ISSUE TITLE
ErrorMsg() still misses reeModifierUnsupported

### ISSUE THREAD

**Issue by AmigoJack** [andgineer/TRegExpr#278]
Version 0.952 did not honor `reeModifierUnsupported` in `ErrorMsg()`, and the current version still misses it, too. It's not really important, but somehow you overlooked it for at least one decade. ;-)

**Comment by Alexey-T** [comment]
I don't get the idea- what to show, where.

**Comment by Alexey-T** [comment]
Made a fix, will be in pull request.

**Comment by Alexey-T** [comment]
@andgineer seems our code detects wrong RE modifiers are gives the error. e.g. here

![Screenshot from 2023-09-20 09-37-34](https://github.com/andgineer/TRegExpr/assets/4154978/8422757c-bf38-4f60-ab35-50150b39e594)

so let's close?
