### ISSUE TITLE
regexpr_unicodedata.pas has wrong CharUpperArray and CharLowerArray mappings

### ISSUE THREAD

**Issue by AmigoJack** [andgineer/TRegExpr#281]
The generated file **regexpr_unicodedata.pas** relies on (wherever the generator is executed) the operating system's support of Unicode, which can vary a lot (most likely lower OS versions yield even worse results) **and** the user localization settings. When I compare it to [the official 1:1 (one codepoint input gives one codepoint output) mapping](https://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt) then I see missing/wrong ranges (GEORGIAN MTAVRULI entirely, GLAGOLITIC CAPITAL LETTER LATINATE MYSLITE, additional LATIN with strokes):
```delphi
  CharLowerArray: packed array[0..$FFFF] of WideChar = (
    ...
    #$10D0, // $1C90
    #$10D1, // $1C91
    #$10D2, // $1C92
    #$10D3, // $1C93
    #$10D4, // $1C94
    #$10D5, // $1C95
    #$10D6, // $1C96
    #$10D7, // $1C97
    #$10D8, // $1C98
    #$10D9, // $1C99
    #$10DA, // $1C9A
    #$10DB, // $1C9B
    #$10DC, // $1C9C
    #$10DD, // $1C9D
    #$10DE, // $1C9E
    #$10DF, // $1C9F
    #$10E0, // $1CA0
    #$10E1, // $1CA1
    #$10E2, // $1CA2
    #$10E3, // $1CA3
    #$10E4, // $1CA4
    #$10E5, // $1CA5
    #$10E6, // $1CA6
    #$10E7, // $1CA7
    #$10E8, // $1CA8
    #$10E9, // $1CA9
    #$10EA, // $1CAA
    #$10EB, // $1CAB
    #$10EC, // $1CAC
    #$10ED, // $1CAD
    #$10EE, // $1CAE
    #$10EF, // $1CAF
    #$10F0, // $1CB0
    #$10F1, // $1CB1
    #$10F2, // $1CB2
    #$10F3, // $1CB3
    #$10F4, // $1CB4
    #$10F5, // $1CB5
    #$10F6, // $1CB6
    #$10F7, // $1CB7
    #$10F8, // $1CB8
    #$10F9, // $1CB9
    #$10FA, // $1CBA
    #$10FD, // $1CBD
    #$10FE, // $1CBE
    #$10FF, // $1CBF
    ...
    #$2C5F, // $2C2F
    ...
    #$A7B9, // $A7B8

    #$A7BB, // $A7BA

    #$A7BD, // $A7BC

    #$A7BF, // $A7BE

    #$A7C1, // $A7C0

    #$A7C3, // $A7C2

    #$A794, // $A7C4
    #$0282, // $A7C5
    #$1D8E, // $A7C6
    #$A7C8, // $A7C7

    #$A7CA, // $A7C9

    #$A7D1, // $A7D0

    #$A7D7, // $A7D6

    #$A7D9, // $A7D8

    #$A7F6, // $A7F5
```
Likewise the other array also has missing/wrong ranges. Please consider using the official file for generating both arrays - doing so is not difficult when sticking to [the explanation of that file's format](http://www.unicode.org/reports/tr44/#UnicodeData.txt):
1. So far, ignore all lines beyond Unicode codepoint U+FFFF.
2. Each line has the same fields, separated by semicolon (`;`) - if you split it correctly you always have 15 fields, where the 1st, the 2nd, the 13th and the 14th are relevant:
   - 1st field = Unicode codepoint of interest (ascending)
   - 2nd field = textual description of character
   - 13th field = which codepoint should be used for the lowercase variant (or empty, if not available)
   - 14th field = which codepoint should be used for the uppercase variant (or empty, if not available)
3. With this knowledge you can ignore all lines where both field 13 and 14 are empty. Or in other words: if the line ends with 3 semicolons (`;;;`) it can be ignored.
4. If the 13th field for the uppercase variant is filled and the 14th field is empty, you have a lowercase letter - you can confirm this by checking if the 2nd field contains the text `SMALL LETTER`.
5. If the 13th field is empty and the 14th field for the lowercase variant is filled, you have an uppercase letter - you can confirm this by checking if the 2nd field contains the text `CAPITAL LETTER`.

Example lines:
```
0052;LATIN CAPITAL LETTER R;Lu;0;L;;;;;N;;;;0072;
0072;LATIN SMALL LETTER R;Ll;0;L;;;;;N;;;0052;;0052
00A2;CENT SIGN;Sc;0;ET;;;;;N;;;;;
0108;LATIN CAPITAL LETTER C WITH CIRCUMFLEX;Lu;0;L;0043 0302;;;;N;LATIN CAPITAL LETTER C CIRCUMFLEX;;;0109;
0109;LATIN SMALL LETTER C WITH CIRCUMFLEX;Ll;0;L;0063 0302;;;;N;LATIN SMALL LETTER C CIRCUMFLEX;;0108;;0108
```
1. The first line's 13th field is empty and the 14th field (`0072`) is filled, so the 1st field (`0052`) is the codepoint of an uppercase letter, pointing to its lowercase counterpart.
2. The second line is the opposite: the 13th field (`0052`) is filled and the 14th field is empty, so the codepoint (`0072`) is a lowercase letter, pointing the the uppercase variant.
3. In the 3rd line both 13th and 14th fields are empty, so this letter/character/codepoint is not interesting for us.
4. The fouth line is just like the first, having the 14th field filled with the lowercase codepoint, meaning we have an uppercase codepoint in this line.
5. The fifth line is the counterpart to the fourth line, just like the second line was for the first line.

If you still find this too challenging I can write the code for it, although not being fluent with FPC. In the meanwhile I will maintain my more complete/correct mapping. Attached my copy - feel free to compare it to your published one.
[regexpr_unicodedata.pas.zip](https://github.com/andgineer/TRegExpr/files/9095899/regexpr_unicodedata.pas.zip)

**Comment by Alexey-T** [comment]
Yes, i find it too challenging, so please make the correct unit for us? (I am the current maintainer)

**Comment by AmigoJack** [comment]
In the archive I have:
- included the most recent download of **UnicodeData.txt** which is needed for extracting the data, file date 2021-07-06
- updated **make_unidata.lpr** to make use of that file and not rely on 
- included the rendered **regexpr_unicodedata.pas** from both the new code and the more accurate data - if you want to compare that file against your version then replace all occurances of `U+` with `$`, as otherwise every line will be different.

[make_unidata.zip](https://github.com/andgineer/TRegExpr/files/9126486/make_unidata.zip)

Further things that should be noted:
- I've changed the comments of f.e. `// $0648` into the proper Unicode codepoint format `// U+0648`.
- The rendered unit now includes comments which have the timestamp of both creating that unit and the last modification date of the Unicode definitions. Also included source URI, so anybody can check if a newer version exists.
- Proper casing of datatypes, f.e. `Byte` instead of `byte`.
- FPC's **unicodedata.pas** is no longer needed. That unit itself is not faulty, but it relies on...
- FPC's **unicodedata.inc** has outdated (comment mentions year 2017), if not wrong definitions (as of FPC 3.2.2). Which is makes them quite pointless. Since it uses its own special format I assume it was rendered, too, instead of written by hand - it must also rely on something and that source should be updated to properly handle Unicode as of today's definitions. **I repeat: do not rely on FPC's Unicode definitions/properties - it's partly wrong!**
- `CharCategoryArray` now also uses the source data file. Since that file does not have 1 line per codepoint I had to detect gaps between codepoints and hard code a bit logic to properly assign a codepoint's category.
- `UpperLowerCase` and `UpperUpperCase` now use the same code.
- I've added a few safeguards that will always output a detailled comment when something unexpected occurs. The only thing I don't check is if the TXT file actually exists - if that's already a problem then you get a runtime error/exception. So it's a good idea to check the rendered file for comments that start with `// Error:`.
- Using `Format()` to avoid dozens of String concatenations.
- Consistent use of uppercase hexadecimal literals (instead of once uppercase and another time lowercase).

Successfully executed with FPC 3.2.2 on Lazarus 2.2.0RC1 from 2021-07-08. And the rendered unit was also successfully used in another Delphi 7 project.

If you include these 3 files then Unicode support of TRegExpr is much better. What remains are codepoints from U+10000 and up - they also have lowercase and uppercase letters. If you also want to support those then just reply to this issue again, so I get a notification and could update **make_unidata.lpr** to also support those. :)
