### ISSUE TITLE
_UpperCase() and _LowerCase() miss compiler directives around "inline;"

### ISSUE THREAD

**Issue by AmigoJack** [andgineer/TRegExpr#282]
These are the only 2 functions where the `inline;` instruction is not enclosed by compiler directives as everywhere else:
```delphi
{$IFDEF InlineFuncs}inline;{$ENDIF}
```
I had to add it after I activated/defined `FastUnicodeData` myself - using Delphi 7 (from 2002) I would otherwise have no chance to use uppercase and lowercase support beyond ASCII - the code either expects FPC or at least Delphi 2009 to allow that, excluding older versions (instead of using **regexpr_unicodedata.pas** always as a fallback when nothing else is available).

Please add the compiler directives and maybe rethink about supporting Delphi versions before 2009 by simply activating/defining `FastUnicodeData` then.

**Comment by Alexey-T** [comment]
Okay , will add directives.

**Comment by Alexey-T** [comment]
Fixed in my fork; PullReq will be little later
