### ISSUE TITLE
TRegExpr compile: unknown meta-character: \R (pos 10) 

### ISSUE THREAD

**Issue by Uefi1** [andgineer/TRegExpr#286]
Hello i need to use \R in my regex but i get error unknown meta-character: \R how can i fix this ?

**Comment by Uefi1** [comment]
\R matches any Unicode newline sequence !

**Comment by Alexey-T** [comment]
Docs tells about it? no! it is not supported.

**Comment by Alexey-T** [comment]
It is not documented in other engines too: https://www.regular-expressions.info/refcharclass.html
what engine supports it?

**Comment by Uefi1** [comment]
I don't know that they wrote me a regular expression where \R is present in notepad++ works

**Comment by Uefi1** [comment]
I Found this in documentation:
https://www.regular-expressions.info/refcharacters.html

**Comment by Alexey-T** [comment]
that table shows: \R is not supported in .NET. only in JGsoft.

**Comment by Alexey-T** [comment]
\R | Matches any line break, including CRLF as a pair, CR only, LF only, form feed, vertical tab, and any Unicode line break
-- | --

supported in Java 8 and Perl 5.10. good idea to add it. maybe later will add it.

**Comment by Alexey-T** [comment]
use English.

**Comment by Uefi1** [comment]
> use English.

Sorry, I thought you were a Russian Serb or Ukrainian)
Can you try to replace this \R with something for now?

**Comment by Alexey-T** [comment]
`(\r\n|\r|\n|\v .....)` must work.

**Comment by Uefi1** [comment]
> `(\r\n|\r|\n|\v .....)` must work.

Exactly how did you write it?
([a-z]+\ )|.+\R+
([a-z]+\ )|.+(\r\n|\r|\n|\v .....)+

**Comment by Alexey-T** [comment]
I mean by `dots` `.....` that your must list all EOL chars or char-pairs

\r\n
\r
\n
\v
others

**Comment by Uefi1** [comment]
([a-z]+\ )|.+(\r\n|\r|\n|\v[a-z])+ ??

**Comment by Alexey-T** [comment]
@user4martin
Do you think it's a good idea? No wish to work on it?
https://github.com/andgineer/TRegExpr/issues/286#issuecomment-1253966374

**Comment by User4martin** [comment]
Good idea, but I haven't got any immediate available time.

**Comment by Alexey-T** [comment]
\R is added. In my fork, let's test it please.
https://github.com/Alexey-T/TRegExpr
If all ok, I will do the PR.

@User4martin @Uefi1
