### ISSUE TITLE
Impossible to use lookahead/lookbehind in combination with boolean "or"

### ISSUE THREAD

**Issue by Bloov** [andgineer/TRegExpr#289]
Example (\{)(?=.*?\})|(?<=\{.*?)(\})
Can't parse following string {13}C{2}H{5}OH
Get error 154: lookaround brackets must be at the very beginning/ending

**Comment by Alexey-T** [comment]
Enclose the regex in backticks, pls.

**Comment by Alexey-T** [comment]
Example `({)(?=._?})|(?<={._?)(})`

**Comment by Alexey-T** [comment]
This regex is bad, it will not be supported. also you must 'escape' chars `{ }`. what text do you want to find ?

**Comment by Alexey-T** [comment]
Ok, why don't you do regex-replace: from string containing all tokens (bad chars) to empty string? Why lookahead/behind is needed?

**Comment by Bloov** [comment]
I think I can do that. The idea was that I need to delete only paired tokens, because these characters are not exclusive for tokens.
