### ISSUE TITLE
Support \h and \v

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#29]
Maybe will make it.
 https://www.regular-expressions.info/shorthand.html

While support for \d, \s, and \w is quite universal, there are some regex flavors that support additional shorthand character classes. Perl 5.10 introduced \h and \v. \h matches horizontal whitespace, which includes the tab and all characters in the "space separator" Unicode category. It is the same as [\t\p{Zs}]. \v matches "vertical whitespace", which includes all characters treated as line breaks in the Unicode standard. It is the same as [\n\cK\f\r\x85\x{2028}\x{2029}].

PCRE also supports \h and \v starting with version 7.2. PHP does as of version 5.2.2, Java as of version 8, and the JGsoft engine as of version 2. Boost supports \h starting with version 1.42. No version of Boost supports \v as a shorthand.

In many other regex flavors, \v matches only the vertical tab character. Perl, PCRE, and PHP never supported this, so they were free to give \v a different meaning. Java 4 to 7 and JGsoft V1 did use \v to match only the vertical tab. Java 8 and JGsoft V2 changed the meaning of this token anyway. The vertical tab is also a vertical whitespace character. To avoid confusion, the above paragraph uses \cK to represent the vertical tab.

**Comment by Alexey-T** [comment]
Done in #31

**Comment by Alexey-T** [comment]
?

**Comment by andgineer** [comment]
Could you please check what's wrong with CI?

https://travis-ci.org/andgineer/TRegExpr/builds/612897961?utm_source=github_status&utm_medium=notification

test/testregexpr: No such file or directory

**Comment by Alexey-T** [comment]
Reason for Travis is #32 - you have too old FPC 2.x which don’t have required unit fpwidestring

**Comment by Alexey-T** [comment]
FPC 3.0.4 is done years ago

**Comment by andgineer** [comment]
I commited to master branch test matrix for CI that check current version with fpc 2.6.x and 3.0.x, on Linux and MacOS.
Current TRegExpr has passed all the tests.

Please merge your branch with current branch and update your PR so we will see test results.
May be that was just a glitch in CI.

**Comment by Alexey-T** [comment]
https://github.com/andgineer/TRegExpr/pull/31 - see my comment there below.
