### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#293]
“Quantifier specifies number of repetition” - missed “s”

**Comment by Alexey-T** [comment]
Typo in GH repo description - Русифицированный fork проекта bottprint-openapi

**Comment by andgineer** [comment]
Sorry I do not get it
Where do you see that?
![iScreen Shoter - Google Chrome app - 230505113408](https://user-images.githubusercontent.com/1568089/236424228-8e2eb6ea-57b8-41d7-9070-c25da515bbf4.jpg)
