### ISSUE TITLE
Feature \G please

### ISSUE THREAD

**Issue by User4martin** [andgineer/TRegExpr#297]
Could \G be implemented please?

https://www.tutorialspoint.com/regular-expression-g-metacharacter-in-java

Also  `ATextStartOffset` in   `FRegEx.Exec(ATextStartOffset)`

**Comment by User4martin** [comment]
@Alexey-T  is this something you could help, please?

**Comment by Alexey-T** [comment]
Maybe ... but I did not understand the text about \G. 
any info on your link.
and on this link- https://stackoverflow.com/questions/14897949/what-is-the-use-of-g-anchor-in-regex

**Comment by Alexey-T** [comment]
first answer here
https://stackoverflow.com/questions/14365969/how-the-anchor-z-and-g-works-in-ruby/14366062#14366062
is good, but I still don't understand this idea.

**Comment by Alexey-T** [comment]
OK I got the idea. after some time.
is is possible in engine - will think...

**Comment by Alexey-T** [comment]
Martin, it is the easy change. i hope you can make the PR. its easy to remember the end of the match after successfull Exec* call, in the new variable, and it's easy to add the `\G` which handler must only compare the current-pos with that variable

I forgot the code, but here is example
```
    '^':
     begin
      if not fCompModifiers.M
        {$IFDEF UseLineSep} or (fLineSeparators = '') {$ENDIF} then
        ret := EmitNode(OP_BOL)
      else
        ret := EmitNode(OP_BOLML);
     end;

    '$':
     begin
      if not fCompModifiers.M
        {$IFDEF UseLineSep} or (fLineSeparators = '') {$ENDIF} then
        ret := EmitNode(OP_EOL)
      else
        ret := EmitNode(OP_EOLML);
     end;
```

so, add OP_PREVIOUS_END const. emit this code like this
```
          'A':
            ret := EmitNode(OP_BOL);
          'z':
            ret := EmitNode(OP_EOL);
```

**Comment by Alexey-T** [comment]
@User4martin Let's close?
