### ISSUE TITLE
Look behind fails when calling Exec(Offset)

### ISSUE THREAD

**Issue by User4martin** [andgineer/TRegExpr#302]
The following test should work.
```
 CompileRE('(?<=.A...)(X)');
 RE.InputString:= '_A123X3';
 IsTrue('Exec must give True', RE.Exec(2));
```

It does work, when called without offset.

But, with offset, it can still look back to before the offset, and therefore should find this. 

The following modified version demonstrates the expectation: https://regex101.com/r/51WHvZ/1

The leading `_|` matches one char, the pattern is global, so it is matched a 2nd time at start-offset = 2. And the result for the 2nd match is success.

**Comment by Alexey-T** [comment]
No idea how to fix, yet.

**Comment by User4martin** [comment]
I will look later / lets concentrate on the big PR first.

**Comment by User4martin** [comment]
This issue can be on hold / it will be closed as side product of implementing better support for all lookaround patterns (in progress)

**Comment by Alexey-T** [comment]
@User4martin Is it solved? Then please close.
