### ISSUE TITLE
wrong 'not fixed op' demo message

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#305]
```
    reg.Compile;
    if reg.IsFixedLength(op, i) then
      ListDump.Items.Add('Fixed length: '+IntToStr(i))
    else
      ListDump.Items.Add('Not fixed op: '+reg.DumpOp(op)); 
```
for 

OP_BOL
OP_EOL
OP_EOL2
OP_BOLML
OP_EOLML
OP_CONTINUE_POS

we get 'not fixed op' string in demo window.
it means 'match has not fixed length'.

![Screenshot from 2023-08-16 10-56-10](https://github.com/andgineer/TRegExpr/assets/4154978/3f2e7207-a75f-444d-98e9-4d439b34cc62)

 it's wrong. theese opcodes are fixed.

**Comment by Alexey-T** [comment]
@User4martin

SUBJ causes fail on this regex:

![Screenshot from 2023-08-16 21-19-34](https://github.com/andgineer/TRegExpr/assets/4154978/14d4a6f6-d633-4358-a30b-63f523ff2716)

let's fix it in IsFixedLength method: find
```
      OP_COMMENT,
      OP_BOUND,
      OP_NOTBOUND
```
and add here:
```
      OP_COMMENT,
      OP_BOUND,
      OP_NOTBOUND,
      OP_BOL,
      OP_BOLML,
      OP_EOL,
      OP_EOL2,
      OP_EOLML,
      OP_CONTINUE_POS:
        Continue; 
```

Pls add this fix to your PR

**Comment by User4martin** [comment]
done

**Comment by Alexey-T** [comment]
solved (in PR).
