### ISSUE TITLE
Wrong match for atomic group

### ISSUE THREAD

**Issue by User4martin** [andgineer/TRegExpr#306]
RegEx `a(?>b.*?c|.)x=..8`
Text: `1ab__cx__9cx__8`

https://regex101.com/r/7Me9rj/1

The atomic group should match `ab__c`. After that, it should not backtrace. So it cant match a longer stretch for the `.*?` part.

But with that match, it can't fulfil the rest of the pattern => therefore the pattern must fail to match.

Yet it matches at Pos=2

**Comment by User4martin** [comment]
Related issue
RegEx `(.)(?>X|Y)b`
Text `1234Xa...56Yb`

It works with regex `(.)(?>Y|X)b`

**Comment by Alexey-T** [comment]
Good finding. I wrote the support for atomics but I forgot the code. Please help with the fix…

**Comment by Alexey-T** [comment]
the first regex in the topic start - needs a fix, '=' is bad char.

**Comment by User4martin** [comment]
> the first regex in the topic start - needs a fix, '=' is bad char.

That was a copy and paste. The `=` should just be deleted.

**Comment by User4martin** [comment]
Fix committed to the collective PR.

Some notes:
```
  RegExprLookaheadIsAtomic: boolean = True;
  RegExprLookbehindIsAtomic: boolean = False;
```

Look ahead is atomic. All it cares is, that it matches once. If then the remainder does not match, the look ahead does not retry.<br/>
This is true, even if the remainder has a back reference to a capture in the look ahead: https://regex101.com/r/lYSu0z/1
- RegEx: `A(?=(bc)|(b))..\2`
- Text: `1Abcb__Ab_b_`
- It matches at pas=7 `Ab_b`
- If the look ahead would backtrace, then the regex would match at pos=1 `abcb` <br/>It would have backtraced the 'bc` in the branch, and tried the `b`, and that would have worked.

Lookbehind currently can't be atomic (limitation of the current implementation).
It must expand to match the position after it:
`(?<=A.*?B)X`  must match `A_BY_BX`. But an atomic would stop at the first "B" (non greedy)

**Comment by Alexey-T** [comment]
>This is true, even if the remainder has a back reference to a capture in the look ahead: https://regex101.com/r/lYSu0z/1

Hey, no! you swapped terms here-

- ahead - is the thing AFTER body
- behind - is the thing BEFORE body

is it right? if so, revert the variables

**Comment by Alexey-T** [comment]
New test from you
```
  IsMatching('Bactrace to before start of atomic - atomic on 2nd pos',
             '(.)(?>X|Y)b',
             '1234Xa...56Yb', [11,3,  11,1]);
```
it means that we had 2 matches as pos=11 - len=3 and len=1 ? is it correct?

**Comment by Alexey-T** [comment]
```
                if IsBacktrackingGroupAsAtom then
                  Exit;
                {$IFDEF ComplexBraces}
                System.Move(SavedLoopStack, LoopStack, SizeOf(LoopStack));
                LoopStackIdx := SavedLoopStackIdx;
                {$ENDIF} 
```
 restoring of LoopStack runs after your new Exit; I hope it is OK.

**Comment by User4martin** [comment]
I'll have to double check ... will update later

**Comment by User4martin** [comment]
There also is another issue - I am looking at - so hold it for now

**Comment by Alexey-T** [comment]
@User4martin Let's close?
