### ISSUE TITLE
Additional syntax for named capture and references/calls.

### ISSUE THREAD

**Issue by User4martin** [andgineer/TRegExpr#326]
The following syntaxes are not yet supported (they give an error, so introducing them does not break existing patterns)

`(?<name>regex)`   for a named capture group

`\k<name>` for a reference (not call) like `(?P=name)`
Also `\k{name}` and `\k'name'` both reference.
Also `\g{name}` and `\g'name'` both reference.

`\g<name>` for a sub-call like `(?P>name)`

`\g1`  same as `\1` but supporting numbers > 9 `\g11` (and also leading zero `\g01`)

regex in action: https://regex101.com/r/7qgquy/1

----

Also added "_" to allowed chars for names. 
`(?P<name_foo>)`

Also shown to work on the above link.

----
new code:
https://github.com/User4martin/TRegExpr/commit/more-references

@Alexey-T 
Can that be added?

**Comment by Alexey-T** [comment]
Good idea. yes, please make the PR.

but: `(regParse + 2)^ in ['=', '!']` - will it work with UnicodeRE, so regParse is PWideChar?

but: \g11 means '1st group and char 1' or '11th group'?

**Comment by User4martin** [comment]
11th group https://regex101.com/r/KsGHat/1 
Group 11 = "B"
\g11 = "b"  (case insensitive)

**Comment by Alexey-T** [comment]
Please add info to regular_expressions.rst:
```
Backreferences
--------------
``
and here
```
Named Groups and Backreferences
-------------------------------
```

**Comment by Alexey-T** [comment]
solved, so let's close?

**Comment by Alexey-T** [comment]
@andgineer Pls close.
