### ISSUE TITLE
Incorrect sub-calls

### ISSUE THREAD

**Issue by User4martin** [andgineer/TRegExpr#329]
Regex `(1(2(3(?1)?))A)_(?3)`
Text `123A_3123`

should match `123A_3`
https://regex101.com/r/1CvVT2/1

Rationale:

- `123` are the leads of each group.
- In the initial run (?1) is not matched (The next char in the Text is `A`, but the call would need `1`)
- After the skipped call the `A_` is matched.
- The call to `(?3)` can not match:
  - Next in the text is `3` => That would still be ok
  - Next in the text is `123` => but in order for the call to `(?1)` to match the text would require an `A` to be included (the capture 1 ends in `A`) 
  - After the call to `(1)` failed the call `(?3) returns => the match ended.

It wrongly returns `123A_3123`
It does not require the mandatory `A` 

The call to `(?1)` contains another run of the 3rd capture (inlined in 1, not called by 1). When the OP_CLOSE of the 3rd capture is reached, it believes this to be the "called (?3)" (which it is not). At this point it falsely returns from the call (therefore not requiring the `A`)

**Comment by Alexey-T** [comment]
`(1(2(3(?1)?))A)`

here it seems - `(?1)` must never match. because `(?1)` is included in 1st group and it calls 1st group. seems, this is bad regex. which must match only with repeat-counter of (?1) is zero.

**Comment by Alexey-T** [comment]
so, maybe we can include the check - sub call must never call surrounding group.

**Comment by User4martin** [comment]
Added fix to #328

**Comment by User4martin** [comment]
> `(1(2(3(?1)?))A)`
> 
> here it seems - `(?1)` must never match. because `(?1)` is included in 1st group and it calls 1st group. seems, this is bad regex. which must match only with zero repeat-counter of (?1).

Add an "A" to the end of the text, and it will match

https://regex101.com/r/1dcWlU/1

**Comment by User4martin** [comment]
An outer caller, can only return after any callee (sub call) has returned.

So, we only need to check OP_CLOSE against the most inner called index. 
Any outer caller index is temp saved, until all inner call have returned.

**Comment by Alexey-T** [comment]
>Add an "A" to the end of the text, and it will match

and how it opposes to my comment? it does not.

**Comment by User4martin** [comment]
> `(1(2(3(?1)?))A)`
> 
> here it seems - `(?1)` must never match. 

Add an "A" and `(?1)` does match.

> because `(?1)` is included in 1st group and it calls 1st group. seems, this is bad regex. which must match only with zero repeat-counter of (?1).

It is not (a bad regex). It is a recursive call. Just a bit more contrived than directly calling itself.

And since it has a `?` it can exit the recursion.

**Comment by Alexey-T** [comment]
Ah, recursive call, now i got idea of that regex.

**Comment by Alexey-T** [comment]
@User4martin It's solved now, let's close?
