### ISSUE TITLE
Code for 'variable amount of groups' needs the rework

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#330]
@user4martin
https://github.com/andgineer/TRegExpr/pull/328/commits/d29f53331d69e675aa0556378e59fa40175f465d

I suggest to rework this code.
currently: all managing of these new arrays is merged into main code.
code is very bad readable!

suggestion: make new type (class) for such arrays, and give it public methods to add items / etc.
move all mananging/reallocs/clearing there.

**Comment by User4martin** [comment]
Just to remove ambiguity: This is with regards to GrpNames? 

They indeed now have code to extend, and clear them, and that code is all over the place.

Te other arrays are still used in the same way as before. They have a single set length call added (and those calls are already in their own place).

Or have I overlooked something?

**Comment by Alexey-T** [comment]
>This is with regards to GrpNames?

Yes, it is

**Comment by User4martin** [comment]
ok.

Other question: Do all version of Delphi that need to be supported have the `object` syntax?
```
type TFoo = object
  Bar: integer;
  procedure DoBar;
end;
```

i.e. used like an advanced record?

Advantage: Does not need to be instantiated.

**Comment by Alexey-T** [comment]
D7 and D10.4 support it. Before D7: must be supported too.

**Comment by Alexey-T** [comment]
D7 (and newer) supports "array of TypeName". D6 or older: IDK.

**Comment by User4martin** [comment]
You mean support of dynamic array?
The code already has `TRegExprCharCheckerInfos = array of TRegExprCharCheckerInfo;`.

So it already is limited to support of dynamic array.

**Comment by User4martin** [comment]
> D7 and D10.4 support it. Before D7: must be supported too. after D10 - i guess yes too.

So `object` is not supported.

Would it be ok, to make it a (non advanced) record? And then have some plain procedure/functions (non-methotds)?

**Comment by Alexey-T** [comment]
>So object is not supported.

`object` IS supported.

**Comment by User4martin** [comment]
> > So object is not supported.
> 
> `object` IS supported.

oh, ok. good.

**Comment by User4martin** [comment]
> I suggest to rework this code. currently: all managing of these new arrays is merged into main code. code is very bad readable!

I should have so done that in first place. 

There is a "matter of preference" question.

When a new regex is parsed, then the current list gets cleared.

I decided to keep some entries in the array (as capacity), so adding new entries will not need to realloc immediately.
But one could also aim to really clear it to free all mem.

IMHO there are 2 main usage pattern of TRegex
- Set reg-expression once, and never change it. I.e. have one TRegEx-instance per expression, avoiding the time to compile the regex over and over. => Then match many strings with it.
- Have a TRegEx-instance and keep changing the expression

In the first case, `clear` doesn't come into play.
In the 2nd case, it is likely that eventually another expression has names and uses the memory

The only case where the `kept capacity` may be a bother, would be some kind of mixed case:
- set an expression
- match lots and lots of inputs
- change the expression, match again, change again....

In that case, if an expression had no names, the memory would be blocked. But to make that matter, one would need lots of TRegEx instances, that all would follow such a usage pattern.

Anyway, I happily change it to `capacity = 0` in `Clear`, if that is preferred.

**Comment by Alexey-T** [comment]
It is OK as is.
