### ISSUE TITLE
Request to re-add the TRegExpr.MatchIndexFromName method

### ISSUE THREAD

**Issue by winddriver** [andgineer/TRegExpr#335]
This method is very useful, why has it been removed from the regexpr.pas unit in the latest version?
Can you add it back?

**Comment by Alexey-T** [comment]
Code has wrapped for it:
```
function TRegExpr.MatchFromName(const AName: RegExprString): RegExprString;
var
  Idx: Integer;
begin
  Result := '';
  if Length(GrpIndexes) = 0 then
    Exit;
  Idx := GrpNames.MatchIndexFromName(AName);
  if Idx >= 0 then
    Result := GetMatch(Idx)
  else
    Result := '';
end;
```

can you use the wrapper? When the original is needed?

**Comment by Alexey-T** [comment]
I posted PR #336 to re-add it.

**Comment by winddriver** [comment]
> I posted PR #336 to re-add it.

Thanks!
Hope the author can merge as soon as possible so that the FPC RTL can be updated as soon as possible

**Comment by Alexey-T** [comment]
@andgineer Pls merge
