### ISSUE TITLE
Sub-call broken in loop

### ISSUE THREAD

**Issue by User4martin** [andgineer/TRegExpr#352]
https://regex101.com/r/tkTwCs/1
`((A)|B|C(?2))*` on `AACB` should match `AA`

But it matches all.

The `(?2)` should re-exec the `(A)`, but the loop uses `InsertOperator` moving the existing OpCodes, but not updating `GrpOpCodes`

**Comment by Alexey-T** [comment]
Per your site,
`(?2) matches the expression defined in the 2nd capture group`

so `(?2)` must match the 'A' letters (2nd group)? in any case, result - the whole string match - looks bad.

**Comment by Alexey-T** [comment]
fixed in the commit  https://github.com/User4martin/TRegExpr/commit/828aa3bfa115d4c0972159ef216b8f343e3c3958 .
