### ISSUE TITLE
op-star prevents match

### ISSUE THREAD

**Issue by User4martin** [andgineer/TRegExpr#353]
https://regex101.com/r/2V42EM/1

`b*` on text= `abcd` is supposed to match the `b`.
Same if the patten is `b*c*` or `(\b|\B)b*` or `x?b*` on text= `abcd`

But it returns empty.

First Charset is "<all chars>", which is correct: after all, if there was no "b" in the expression, then it would match empty at the start.

But it should not give up, after matching empty.

**Comment by User4martin** [comment]
Actually, the website got me there. It has opt-global on by default.
The behaviour is only if global is turned on.

TRegEx does not have that yet (yet TRegEx has ExecPos to do what global would do.

So how to handle?
Do we need the global flag?

**Comment by Alexey-T** [comment]
I am not sure that `b*` must match the `b`, it can match empty string and it is doing this. looks like other engines have some option for this case? and we don't.

**Comment by Alexey-T** [comment]
I am not sure how much we need the 'global flag to fix this'. which other RE engines have it? only 1 or 2 from totally 10?

**Comment by User4martin** [comment]
Actually you are right...

I either had a severe issue with my vision, or they update the page.

Looking at it today, it shows that `b*` does match the empty, but as it is global, it matches again (and for an empty pattern the next match is at "previous end +1" (which for TRegEx is up to the user-code, and that's fine).

So we actually do the correct thing.

**Comment by Alexey-T** [comment]
thanks. I dont know what is 'global match' at the www site.
