### ISSUE TITLE
Delphi 12 changes

### ISSUE THREAD

**Issue by dkounal** [andgineer/TRegExpr#367]
Try to compile with Delphi 12
a) regexpr_compiler.inc needs to have VR360 added
b) Line 634 and 653 the "overload;" must be before "inline;" eg
```
    function Exec(const AInputString: RegExprString): Boolean; {$IFDEF OverMeth}overload;{$endif} {$IFDEF InlineFuncs}inline;{$ENDIF}
    {$IFDEF OverMeth}

```
```
    function ExecPos(AOffset: Integer {$IFDEF DefParam} = 1{$ENDIF}): Boolean;{$IFDEF OverMeth}overload;{$endif} {$IFDEF InlineFuncs}inline;{$ENDIF}
    {$IFDEF OverMeth}

```
c) Line 2585
[DCC Error] regexpr.pas(2585): E2441 Inline function declared in interface section must not use local symbol 'OP_BRANCH'

**Comment by Alexey-T** [comment]
thanks for report. i made changes w/o testing it in Delphi. Pls test.

**Comment by dkounal** [comment]
Works OK. Thank you!
