### ISSUE TITLE
Nested back-ref does not work

### ISSUE THREAD

**Issue by User4martin** [andgineer/TRegExpr#376]
A back-ref `\1` matches the same literal text as was matched by the most recent successful capture of the group.

That is, if the group is matched in a loop, then it will be the text matched in the most recent iteration.

But
```
  IsMatching('nested ref', '(?i)^(.(?:(\1)|(.)))*',  'aAaaAa',  [1,5,  3,3, 4,2, 2,1]);
```

The `\1` is within the group 1.
- In the first loop it has nothing to match.
- In the 2nd loop, it can and should match the result from the first iteration.

https://regex101.com/r/sstaLI/1

In TRegExpr it does not.

**Comment by Alexey-T** [comment]
Do all / most engines support \1 inside group-1. it sounds scary. maybe it's rare feature.

**Comment by User4martin** [comment]
If they support \1 at all, then they supported it nested too.

ECMA handles it different (independent of nested or not)
Given `(?: (?:\1|\d) (\w) )*`

In the first loop the capture 1 `(\w)` has not yet been maatched.
- All engines will therefore fail to match `\1` in the first iteration. But may match it in the 2nd iteration.
- ECMA will match the empty string for that `\1` in the first iteration.

Same holds true in the nested case. Which really is no different, from a users view. It only is different for the implementation, because the new match must be written in one go only when the `)` is reached, so the last match is valid until the next is fully avail.
