### ISSUE TITLE
Better remove macOS from CI

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#38]
macOS tests run SLOOWLY, first VM is installing 100*k packages, then VM installs 100M Lazarus package, it runs for 9minutes already, all Linux tests are passed long ago.

**Comment by andgineer** [comment]
But this is what CI is for..
You can check on you machine - in seconds.
And after that CI will check everything thoughtfully - no need to wait it..

**Comment by andgineer** [comment]
removed - now tests run only for 3 versions of FPC in linux
1:20 each, generally runs in parallel
