### ISSUE TITLE
Version prop is not needed

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#42]
v. 0.947 2001.10.03
 -=- (+) VersionMajor/Minor class method of TRegExpr ;)

после применения #41 предлагаю удалить эти два св-ва, какой в них смысл? только вывести что-то в окне REStudio? для программиста важен код и там в history.txt версия есть. даже REStudio может вывести эту версию без этого свойства.

**Comment by Alexey-T** [comment]
Кстати, я предложил такое же проперти Version удалить из python 4 Delphi и автор согласилась, не нужно это.

**Comment by Alexey-T** [comment]
@andgineer ?

**Comment by andgineer** [comment]
Sorry I disagree.
It's good if you can check version programmatically.

And in any case I do not see a strong case to break backward compatibility.
