### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#43]
https://regex.sorokin.engineer/en/latest/regular_expressions.html#predefined-character-classes

here \h, \v are missed.

**Comment by Alexey-T** [comment]
URL in description of GH repo is dead
http://regexpr.masterandrey.com/en/latest/

**Comment by andgineer** [comment]
Thank you
https://github.com/andgineer/TRegExpr/commit/dd7cc88c23d691ccbf7dbea28d4d2834224110d4
