### ISSUE TITLE
Remove WordChars, SpaceChars props, add hardcoded Unicode checks for them

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#44]
для своего CudaText хочется сделать такие правки.
предлагаю удалить проперти WordChars, SpaceChars и заменить их hardcoded checks.

и то и то делается просто и надежно. зачем вообще ввели это WordChars, я понимаю так что людям не хотелось делать полноценный анализ UnicodeData но хотелось детектить многие буквы - вот и приделали WordChars.
но это криво - оно и медленно и все буквы нереально туда записать, в юникод их очень много, многие запишут туда только латинские умляуты, а другие языки как? кто-то еще пропустит греческий, кто-то русский. а есть еще азиатские- их почти все пропустят (там Jap, Chinese, Korean, Indian итд).
hardcoded checks будут работать быстро - быстрее проверки 20-40 букв, там проверки по UnicodeData.

для SpaceChars тоже быстро, тоже проверка по UnicodeData.
проверки UnicodeData будут в ifdef unicode.

даете добро на пач?
@andgineer

**Comment by andgineer** [comment]
Изначально идея была в том что я TRegExpr использовал скорее как некий инструмент и в эти множества запихивал даже вообще не буквы а нечто что мне надо было на тот момент для конкретной задачи.
И возможно кто-то сейчас делает также и мы им поломаем обратную совместимость.

Может стоит подумать про оптимизацию - как препроцессить эти списки букв чтобы далее при обработке текста быстро искать ане бегать каждый раз по списку.
Уже простейшая сортировка и binary search наверно могут улучшить ситуацию.. Хотя без тестов на производительность все это очеь вилами по воде - если смотрел доклад Александреску на CppCon то с современными процессорами из-за branch prediction на маленьких массивах binary search работает медленнее тупого линейного сканирования. Кстати в старых процессорах все было еще печальнее - там вообще ошибка предсказания приводила к тому что в мусорное ведро отправляется море уже проделанной работы.

Так что пока нет тестов производительности трудно что-то внятное понять..

**Comment by Alexey-T** [comment]
>И возможно кто-то сейчас делает также

а разве можно запихивать в wordchars не буквы? это нарушение нотации regex- такой компонент уже не по стандарту, а стандарт на \w это alphanumerical+'_'.

**Comment by Alexey-T** [comment]
если в wordchars запихнуть некие спец символы regex (`#$^+*?`) то вообще все плохо будет.

**Comment by andgineer** [comment]
это же просто свойство компонента
в своей программе я могу класть туда то что мне нужно - стандарт тут ни при чем, если я использую это внутри своего приложения для решения своей задачи
в которой понятие "символы слова" может отличаться

**Comment by Alexey-T** [comment]
как бы хорошо выбросить эту фичу (wordchars, spacechars), смотрите как код можно упростить.
```
          'd': begin // r.e.extension - any digit ('0' .. '9')
             ret := EmitNode (ANYDIGIT);
             flagp := flagp or HASWIDTH or SIMPLE;
            end;
          'D': begin // r.e.extension - not digit ('0' .. '9')
             ret := EmitNode (NOTDIGIT);
             flagp := flagp or HASWIDTH or SIMPLE;
            end;
```

видим что для классов \d \D делается опкод, и никаких цифр не пишется в опкод.

а теперь что делается для поддержки wordchars, spacechars-

```
          's': begin // r.e.extension - any space char
             {$IFDEF UseSetOfChar}
             ret := EmitRange (ANYOF);
             EmitRangeStr (SpaceChars);
             EmitRangeC (#0);
             {$ELSE}
             ret := EmitNode (ANYSPACE);
             {$ENDIF}
             flagp := flagp or HASWIDTH or SIMPLE;
            end;
          'S': begin // r.e.extension - not space char
             {$IFDEF UseSetOfChar}
             ret := EmitRange (ANYBUT);
             EmitRangeStr (SpaceChars);
             EmitRangeC (#0);
             {$ELSE}
             ret := EmitNode (NOTSPACE);
             {$ENDIF}
             flagp := flagp or HASWIDTH or SIMPLE;
            end;
          'w': begin // r.e.extension - any english char / digit / '_'
             {$IFDEF UseSetOfChar}
             ret := EmitRange (ANYOF);
             EmitRangeStr (WordChars);
             EmitRangeC (#0);
             {$ELSE}
             ret := EmitNode (ANYLETTER);
             {$ENDIF}
             flagp := flagp or HASWIDTH or SIMPLE;
            end;
          'W': begin // r.e.extension - not english char / digit / '_'
             {$IFDEF UseSetOfChar}
             ret := EmitRange (ANYBUT);
             EmitRangeStr (WordChars);
             EmitRangeC (#0);
             {$ELSE}
             ret := EmitNode (NOTLETTER);
             {$ENDIF}
             flagp := flagp or HASWIDTH or SIMPLE;
            end;
```

видим что тут зависит от define -  или пишется опкод ANYLETTER, NOTLETTER (что с поддержкой юкинодных букв будет так же быстро(, или делается писание всех букв в опкод (что конечно нельзя делать для всех юникодных букв).

**Comment by Alexey-T** [comment]
тогда нам надо бы убрать поддержку IFDEF UseSetOfChar - при этом wordchars / spacechars останутся и при доработке IsWordChar / IsSpaceChar все заработает для юникода. тогда вопрос- зачем вам этот   IFDEF UseSetOfChar - почему его не убрать?

**Comment by Alexey-T** [comment]
Ok, я сделаю юникод детект под новым define или под ifdef UnicodeWordDetection
