### ISSUE TITLE
[Fatal Error] RegExpr.pas(735): File not found: 'System.Character.dcu' on D7

### ISSUE THREAD

**Issue by breti** [andgineer/TRegExpr#48]
There seems to be an issue with ifdef statements for D7:

[Fataler Fehler] RegExpr.pas(735): Datei nicht gefunden: 'System.Character.dcu'
[Fatal Error] RegExpr.pas(735): File not found: 'System.Character.dcu'

I had to comment out the following lines:
// uses
//  System.Character; // System.Character exists since Delphi 2009

D7 Build 4.453, TRegExpr latest

**Comment by Alexey-T** [comment]
I will add Ifdef so Delphi 2009 code will be not used on D7, I wait for #41 apply

**Comment by Alexey-T** [comment]
@andgineer Solved, close it.

**Comment by andgineer** [comment]
Lets wait a couple of days for @breti to close it

**Comment by breti** [comment]
Thanks a lot! The fix is working fine.
