### ISSUE TITLE
Single pass of regex compiler?

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#55]
@andgineer хочу попробовать сделать только 1 проход. пока их два- 1й считает размер программы, 2й уже пишет программу в буфер. как сделать только один? сразу выделять память и писать в буфер, делая ReallocMem при увеличении буфера. делаем realloc шагами по Н символов (предлагаю дать Н=100). многие выражения коротки и уместятся в 100-300 символов, что требует только 2 реаллока. добро?

**Comment by andgineer** [comment]
Изначально идея была в том что распарсить лишний раз не проблема, а realloc это очень догостоящее развлечение.

Без тестов быстродействия я просто не стал делать такой рефакторинг - как понять сделаешь быстрее или наоборот?

**Comment by Alexey-T** [comment]
Ok
