### ISSUE TITLE
\w \W - opcode or string?

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#56]
ParseAtom имеет такой код для \d \D

```
          'd': begin // r.e.extension - any digit ('0' .. '9')
             ret := EmitNode (ANYDIGIT);
             flagp := flagp or HASWIDTH or SIMPLE;
            end;
          'D': begin // r.e.extension - not digit ('0' .. '9')
             ret := EmitNode (NOTDIGIT);
             flagp := flagp or HASWIDTH or SIMPLE;
            end;
```
тут делается опкод ANYDIGIT или обратный. ОК
для \w \W делается не так - тут или опкод или Emit строки wordchars

```
          'w': begin // r.e.extension - any english char / digit / '_'
             {$IFDEF UseSetOfChar}
             ret := EmitRange (ANYOF);
             EmitRangeStr (WordChars);
             EmitRangeC (#0);
             {$ELSE}
             ret := EmitNode (ANYLETTER);
             {$ENDIF}
             flagp := flagp or HASWIDTH or SIMPLE;
            end;
```

почему не делать тут всегда опкод? это же лучше вроде - тогда UseUnicodeWordDetection отработает для этого случая тоже (а пока оно где то видимо работает а где-то нет). @andgineer 

вот где юзается UseUnicodeWordDetection:

```
function TRegExpr.IsWordChar(AChar: REChar): Boolean;
begin
  Result := Pos(AChar, fWordChars)>0;
  {$IFDEF UnicodeWordDetection}
  If Not Result and UseUnicodeWordDetection then
    Result:=IsUnicodeWordChar(aChar);
  {$ENDIF}
end;
```

**Comment by Alexey-T** [comment]
хочу добавить UnicodeWordDetection для Делфи 2009+, но как оно будет работать если я добавлю его в IsWordChar а в это место кода (Emit строки) не добавлю? надо сделать юзание fWordChars в одном!! месте.

**Comment by andgineer** [comment]
Как мы уже обсуждали, возможность иметь кастомные наборы символов использовалась ранее лично мной чтобы на базе этого движка создавать что-то специализированное, для разбора текстов где "слово" имеет какое-то свое, специфичное для прикладной области значение.

Но поскольку эффективнее конечно работает специфический опкод, и был введен  UseSetOfChar.

Нужно тебе такое специфическое использование - включаешь его, тогда движок сравнивает с набором символов, коотрый ты можешь менять. Не нужно - не включай и тогда будет компактный и быстрый опкод ANYLETTER.

Надо ли это убирать? Если не нужно такое специфическое использование то просто не включай  UseSetOfChar.

**Comment by Alexey-T** [comment]
значит UseSetOfChars делалось для поддержки WordChars/ SpaceChar properties? а не для какой-то оптимизации?

```
{$IFNDEF UniCode} // the option applicable only for non-UniCode mode
 {$IFNDEF FPC_REQUIRES_PROPER_ALIGNMENT}  //sets have to be aligned
 {$DEFINE UseSetOfChar} // Significant optimization by using set of char
 {$ENDIF}
{$ENDIF}
```

**Comment by Alexey-T** [comment]
не понимаю код. хочу у себя поменять (по опции!) fWordChars на другое, тогда надо убрать везде fWordChars.
вот тут как его менять?
это код парсинга внутри `[]`.
```
          begin
            if regparse^ = EscChar then
            begin
              Inc(regparse);
              if regparse >= fRegexEnd then
              begin
                Error(reeParseAtomTrailingBackSlash);
                Exit;
              end;
              case regparse^ of // r.e.extensions
                'd':
                  EmitRangeStr('0123456789');
                'w':
                  EmitRangeStr(WordChars);
                's':
                  EmitRangeStr(SpaceChars);
                'v':
                  EmitRangeStr(RegExprLineSeparators);
                'h':
                  EmitRangeStr(RegExprHorzSeparators);
              else
                EmitSimpleRangeC(UnQuoteChar(regparse));
              end; { of case }
```
заменил EmitRangeStr(WordChars) на EmitNode(OP_ANYLETTER), тесты работают.

1) а почему вы не поставили тут EmitNode?
2) видимо в этом месте не работают юникодные буквы (UnicodeWordDetection).
как это проверить?
@andgineer

**Comment by andgineer** [comment]
для d видимо можно и emitnode а остальное уже под опцией - исплоьзуем множества или фиксированные списки для символов слов или нет

а откуда версия что юникод не работает - он же использует WordChars
проверить - в тесте вставить юникод в текст который ищет конструкция []

**Comment by Alexey-T** [comment]
ОК. уточните еще вот что-- для быстрого детекта ASCII wordchars (a..z A..Z 0..9 _ ) мне надо убрать под define весь код с полем fWordChars. какой define сделать? сделать новый define UseWordChars или заюзать готовый UnicodeWordDetection (когда он вкл, то поле убирается)?

**Comment by andgineer** [comment]
UnicodeWordDetection включает для юникода эвристику определения что перед нами символ слова внутри IsWordChar

UseSetOfChar изначально был совершенно конкретной оптимизацией - если нам нужно сравнить символ с МАЛЕНЬКИМ набором символов (короче TinySetLen) то мы клали набор символов в set который позволял очень быстро определить есть ли символ в наборе.

сейчас под этой опцией если она включена то вставляется в опкод множество fWordChars иначе вставляется опкод ANYLETTER который использует функцию IsWordChar

мне кажется конкретно это уже какая-то глупость
нет смысла вставлять в опкод перечень fWordChars если можно вставить опкод который ровно с этим набором символов и сравнивает

что касается "для быстрого детекта ASCII wordchars (a..z A..Z 0..9 _ )" очевидно это надо изменить функцию IsWordChar и тут напрашивается новый define, UseWordChars выглядит логично
хотя мне и кажется что была уже какая-то опция на эту тему

**Comment by Alexey-T** [comment]
«эвристика» есть догадка, а там четкий детект по unicodedata.
Ok. Todo
