### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#61]
![ww](https://user-images.githubusercontent.com/4154978/69990878-9dae3800-1557-11ea-8238-7ef2af7c4016.png)

- зачем тут второй пример для \tfoobar? уже есть для \t.
- лучше всю инфо про \ci поместить в одну строку а не в 3

**Comment by Alexey-T** [comment]
- про \ci  надо написать что буква - это lowercase / uppercase 'a' to 'z'

**Comment by andgineer** [comment]
https://github.com/andgineer/TRegExpr/commit/0306d15e1766d116c588b460dbad1216cf50cb4f
