### ISSUE TITLE
Small optimization: replace regdummy to bool flag

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#62]
предлагаю такую мелкую оптимизацию. убрать regdummy (идет проверка `if p = @regdummy` чтобы понять что это первый проход - посчитать размер программы), заменить его на флаг DummyPass: boolean. чуть лучше. @andgineer ok?

**Comment by andgineer** [comment]
Честно говоря не совсем понял что именно это улучшит

**Comment by Alexey-T** [comment]
Ничего, только код читаться будет немного проще....
