### ISSUE TITLE
Format src 

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#65]
I can format source code a little, by mass replaces

- delete spaces before ( and [
- delete spaces before : and :=
- lowercase some keywords: Const Var
- title case EXIT

Ok? @andgineer

**Comment by andgineer** [comment]
Well no preferences in code formatting from my side.

We better choose some standard way for Pascal but I am not familiar with any.

**Comment by Alexey-T** [comment]
I suggested the standard way... in Lazarus there is also internal code Formatter but I suggested manual mass replace anyway

**Comment by andgineer** [comment]
Ok but I suggest to add link to some code style so we would have some rules, and not just personal opinion.

**Comment by Alexey-T** [comment]
Lazarus code
https://github.com/graemeg/lazarus/tree/upstream/ide
I opened random .pas/.pp files, and all have 

- no spaces before ( and [, 
- no space before `:`, 
- but `:=` is surrounded by 2 spaces or 0 spaces (mostly with 2 spaces), 
- `var`, `const` are in lowercase, 
- `function`, `procedure` in lowercase, 
- `exit` in different case (often `exit`).

**Comment by andgineer** [comment]
I meant we need a link to some DOCUMENT with description what code style we want in the library.

You see code style often is a hot question with a lot of debates around.
So if we can say - just read this rules, that could prevent all this fruitless discussions.

**Comment by andgineer** [comment]
If you do not know such a resource may be place on github wiki very short description of the rules you want to have in the code

**Comment by Alexey-T** [comment]
I may write this doc.
Or we can use Embarcader Formatter.exe (it's in Delphi community edition, free).
http://docwiki.embarcadero.com/RADStudio/Rio/en/Formatter.EXE,_the_Command_Line_Formatter

Ok to format with Formatter.exe?

**Comment by Alexey-T** [comment]
I used the Formatter.exe from Delphi Commonity 10.3, here is the result, post this file, no need to make a pullreq.
[RegExpr-fmt.zip](https://github.com/andgineer/TRegExpr/files/3928498/RegExpr-fmt.zip)

**Comment by andgineer** [comment]
it's ok

**Comment by Alexey-T** [comment]
So post the file to GH
