### ISSUE TITLE
How to refactor here? test fails

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#78]
есть такая часть
```
              case regparse^ of // r.e.extensions
                'd':
                  EmitRangeStr('0123456789');
                'w':
                  {$IFDEF UseWordChars}
                  EmitRangeStr(WordChars);
                  {$ELSE}
                  EmitNode(OP_ANYLETTER);
                  {$ENDIF}
```

тут пробую сделать замену- по аналогии с \w \s
```
                  //EmitRangeStr('0123456789');
                  EmitNode(OP_ANYDIGIT);
```

но это сразу дает сбой Test11.
```
    (
    expression: '[^\d]+';
    inputText: '234578923457823659ARTZU38';
    substitutionText: '';
    expectedResult: 'ARTZU';
    matchStart: 19
    ),
```
видимо такая замена неверна для понимания `[^\d]` . уже нехорошо. и подозрение что тогда и код для \w тоже нехорош - он даст сбой в `[^\w]`. надо проверить.
что делать?

**Comment by Alexey-T** [comment]
при детекте символа ^ после [ можно запомнить var InverseClass:bool, и тогда при EmitNode надо проверять InverseClass, и если оно true, делать EmitNode обратного кода (BUTDIGIT) а не прямого (ANYDIGIT).
видимо так?

**Comment by Alexey-T** [comment]
попробовал это поправить так
```
              case regparse^ of // r.e.extensions
                'd':
                  begin
                    //EmitRangeStr('0123456789');
                    if bInverse then
                      EmitNode(OP_NOTDIGIT)
                    else
                      EmitNode(OP_ANYDIGIT);
                  end;
```
где выше делается 
```
        bInverse := regparse^ = '^';
        if bInverse then
        begin // Complement of range.
          if (fCompModifiers and MaskModI) <> 0 then
            ret := EmitRange(OP_ANYBUTCI)
          else
            ret := EmitRange(OP_ANYBUT);
          Inc(regparse);
        end
        else if (fCompModifiers and MaskModI) <> 0 then
          ret := EmitRange(OP_ANYOFCI)
        else
          ret := EmitRange(OP_ANYOF);
```
но это не помогло. Test11 все равно сбоит.
тогда тут кривое место - это место парсинга внутри `[ ]` для \d \w \s и тд.
что делать? @andgineer

**Comment by Alexey-T** [comment]
судя по обработке опкода для `[ ]` 
```
    OP_ANYOF:
      while (Result < TheMax) and (StrScan(opnd, scan^) <> nil) do
      begin
        Inc(Result);
        Inc(scan);
      end;
    OP_ANYBUT:
      while (Result < TheMax) and (StrScan(opnd, scan^) = nil) do
      begin
        Inc(Result);
        Inc(scan);
      end;
    OP_ANYOFCI:
      while (Result < TheMax) and (StrScanCI(opnd, scan^) <> nil) do
      begin
        Inc(Result);
        Inc(scan);
      end;
    OP_ANYBUTCI:
      while (Result < TheMax) and (StrScanCI(opnd, scan^) = nil) do
      begin
        Inc(Result);
        Inc(scan);
      end;
```
опкод всегда сканируется от OP_.... до нуля и никакие вложенные опкоды типа ANYLETTER ANYDIGIT ANYSPACE не разрешены. это нехорошо так сделали.

**Comment by Alexey-T** [comment]
предлагаю сделать так.
для опкода внутри [ ] сейчас пишется поток символов и в конце 0.
сделать так.
писать поток ПАР символов. (kind, char). тогда при сканировании опкода можно смотреть на пары и если например 

- kind=1, то char это "просто символ", 
- kind=0, то это конец [ ]
- kind=2, то это место \w
- kind=3, это место \W

там мы поддержим вообще все штуки \w \W \d \D \s \S \v \V \h \H внутри [ ]

**Comment by andgineer** [comment]
компактнее будет иметь опкоды для всех фиксированных подмножеств и для конца []
причем можно использовать те же опкоды что и снаружи []

а наборы сиволов писать парой - опкод "набор символов" и его длина, дальше сами символы

вообще вроде где-то еще использовался тот факт что [] это именно перечень символов, так что фиксированные множества в него не вставить - как минимум оптимизация которая определяет с какого символа может начинаться искомый текст если в начале регулярного выражения []

но надеюсь это выявят тесты
