### ISSUE TITLE
For user class ']'at the beginning does not included into class

### ISSUE THREAD

**Issue by andgineer** [andgineer/TRegExpr#81]
https://regex.sorokin.engineer/en/latest/regular_expressions.html#user-character-classes
"If you want ] or [ you may place it at the start"
but in fact we do not do that:
https://github.com/andgineer/TRegExpr/blob/61701cb4f0a53f7001ba9a0867352f962b9ad3ce/src/RegExpr.pas#L1010

**Comment by andgineer** [comment]
@Alexey-T could you fix that? and add tests for re like '[[ab]', '[]ab]'?

**Comment by Alexey-T** [comment]
Will try it

**Comment by Alexey-T** [comment]
Line 1010 is in the func RegExprSubExpressions, so the issue is in this func? Or it’s everywhere? Repro steps?

**Comment by andgineer** [comment]
It checks for “]” as first char inside [] and in this case includes it into the char set.
But also it have to check also for “[” so we can use re “[[ab]*” to find string like “a[b”

To chech that we need tests with re like “[[ab]” and “[]abab]

**Comment by andgineer** [comment]
May be I found wrong line - it shoud be inside re parser

**Comment by Alexey-T** [comment]
What wrong line, sorry ?

**Comment by andgineer** [comment]
Line 1010
As I see it should be
https://github.com/andgineer/TRegExpr/blob/61701cb4f0a53f7001ba9a0867352f962b9ad3ce/src/RegExpr.pas#L2807

but we have to support this syntax in  RegExprSubExpressions too

**Comment by Alexey-T** [comment]
Pull request, with test 38

**Comment by andgineer** [comment]
silly me - we do not need to check for '[' because user class ("[]") includes just any char but ']'.
so we should check only for ']' at first position.
