### ISSUE TITLE
Better find in char classes

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#91]
После патча #90  ещё сделаю 

- запись в опкод имён мета классов , а не всей строки вида DigitChars, WordChars, SpaceChars
- будет работать инверсные \W \S \D внутри []
- писать диапазоны `a-x` как два кода а не как всю строку от начала до конца

**Comment by Alexey-T** [comment]
@andgineer диапазоны сделал, пишу их как два кода. это даст супер фаст проверку для больших диапазонов типа a-z.

**Comment by Alexey-T** [comment]
сделал остальное - см выше!

**Comment by Alexey-T** [comment]
еще сделаю testcase для новых фич - null in []. \W \S \D in [].

**Comment by Alexey-T** [comment]
@andgineer пач готов но я не понимаю вот что. как движок делает прыг ЗА ПРЕДЕЛЫ символов char class, которые у вас были записаны как REchar string + NULL.
мне надо поправить этот прыг!

**Comment by Alexey-T** [comment]
жду принятия пача. потом буду убирать все что делается от define UseCharSet ли как оно там называется--- т к при определении этого define с новым опкодом все портится, примите пач и дам пач cleanup.  @andgineer

**Comment by andgineer** [comment]
Поддержка диапазонов - хорошая идея, это заметно ускорит работу с большими диапазонами надо только настроить минимальную длину - мне кажется если у нас там всего несколько подряд идущих символов то мы больше потеряем на промахах чем при простом последовательном сравнении.

Тут как раз очень не хватает тестов производительности с помощью которых можно было бы легко проверить гипотезу о производительности.
Может сделаешь что-то простое?
Видимо надо в цикле гонять уже имеющиеся тесты - для чистоты эксперимента можно в них отключать например $IFDEF проверку результата чтобы не замыливать результат работой обвязки теста.

Что касается произвольного набора символов то наверно не надо к каждому приписывать тип - это и некрасиво и неэффективно. Нужен тип "далее N символов" такой же как для диапазона символов.

**Comment by Alexey-T** [comment]
Попробую все это сделать- давайте я примем пач и я очищу старое от define UseCharSet, и отколы для tinyLen

**Comment by Alexey-T** [comment]
Сделал эту оптимизацию- OpKind_Char пишется компактно ( char(6)+length , затем все символы строки)
