### ISSUE TITLE
Restore FillFirstCharSet optimization

### ISSUE THREAD

**Issue by andgineer** [andgineer/TRegExpr#97]
It significantly improves speed for large input text - we fast skip all positions that are not worth executing full blown re engine.

**Comment by andgineer** [comment]
I think we can limit it to 32 chars - so if we analize re and see no more than 32 potintial start chars we place them into set of char and use for the optimization - fast forwarding inside input text.
If there are more - well just do not use the optimization.

**Comment by Alexey-T** [comment]
Done, in pull req.

**Comment by Alexey-T** [comment]
@andgineer close it?
