### ISSUE TITLE
Give error for [\1\Z]

### ISSUE THREAD

**Issue by Alexey-T** [andgineer/TRegExpr#99]
if meta chars are not allowed in [], it is not handled, and no error shows.
e.g. try regex [\1] or [\Z] - this gives char '1' in [], char 'Z' in [].
suggestion- show error here.
```
            if regparse^ = EscChar then
            begin
              Inc(regparse);
              if regparse >= fRegexEnd then
              begin
                Error(reeParseAtomTrailingBackSlash);
                Exit;
              end;
              if _IsMetaChar(regparse^) then
              begin
                AddrOfString := nil;
                CanBeRange := False;
                EmitC(OpKind_MetaClass);
                EmitC(regparse^);
              end
              else
              begin
                EmitSimpleRangeC(UnQuoteChar(regparse));
               //!! error
              end;
```

**Comment by Alexey-T** [comment]
@andgineer Ok to do?

**Comment by andgineer** [comment]
This is unclear for me.
Now we CAN have meta-chars inside [] like \s, \W and so on.
But also we can use "escaped" simple chars for example [a\-z] - so this is not range a-z but just three chars 'a', '-', 'z'. So we do nee escaping inside [].
as well as \x20 for example.

Why do you want to raise an error?
